# Module Information {-}

If you'll read one page of this entire workbook in depth, please make sure it is **this one!**. 

The following page outlines exactly **how** we hope you will engage with online learning for this course. Running a **practical-based** course online is not easy - for both lecturers and students alike! 

To help, we've tried to break down our content into short chunks, using a mix of recorded lecture videos, recorded practical and coding videos, as well as recommended reading and even short explanations of our own.

## Self-guided learning for Geocomputation {-}

The majority of your learning this year for Geocomputation will be 'self-guided' - however this is not to say, you'll be learning alone. We'll be running **fortnightly seminars** to check-in on your progress and discuss what you've learnt in our small groups (attendance is recorded), whilst also encouraging you to attend (optional) **Help/ Study Group sessions** on the weeks the seminars are not held. In addition, you'll have small **Assignments** to complete, that we're (time-permitted) hoping to provide you with small feedback on, either during the seminars or through discussion forums (held either on Teams or Moodle, depending on requirements, instructions will be provided as and when).

### Geocomputation Timetable {-}

A typical fortnight for Geocomputation will look something like this:

* **Tuesday 10am:** New content is released.
* **Friday 5pm:** Post/Send Assignment submissions for online feedback (*Optional, but recommended*)
* **Monday/Tuesday (allocated slots):** Help/Study Group, run by Jakub and Nikki - get help on your practical work if you've been unable to submit your work,  bring articles you've read for discussion, discuss your feedback, and catch-up with friends!
* **Tuesday 10am:** New content is released.
* **Friday 5pm:** Post/send assignment submissions for seminar (*if required*)
* **Monday/Tuesday (allocated slots):** Seminar, run by Jo - discuss content for the last two weeks, bring articles you've read for discussion, discuss your feedback, and ask questions!

And repeat! 

There will of course be a break for Reading Week where we will set you a short Coding Challenge to complete ready for the seminar at the start of the second half of term. 

In addition to our scheduled fortnightly help sessions, there will also be the weekly **Coding Therapy** classes run by PhD students within the Department to help you with coding issues if you get stuck and can't wait for our help sessions. 

*Please do use these classes in addition to our Help Sessions - they are there to help you with any module that requires any type of programming, not just Geocomputation, as well as your Dissertation!*

We will also provide some additional help sessions in the first two weeks of the Easter break to help you with your first Assessment. The hours for this are TBC.

### What will I be learning each week? {-}

As you'll soon find out, you will learn **a lot** of different things in Geocomputation - from spatial analysis techniques to understanding how to write code to process and analyse data, as well as how to organise your investigation and use statistical and spatial analysis to answer research questions. 

To help, we have broken the course into three main sections:

* **Foundational Concepts**

* **Core Spatial Analysis** 

* **Advanced Spatial Analysis**

We hope this helps with the various learning curves you're about to embark on - as outlined and explained further in Week 1's content.

The topics covered over the next ten weeks are:

| Week          | Date          | Section | Topic | Online Session |
| :------ |:-----|:--------------|:----- |:----- |
| 1             | 11/01/2021    | Foundational Concepts | Geocomputation: An Introduction | N/A|
| 2             | 18/01/2021    | Foundational Concepts | GIScience and GIS software | Seminar |
| 3             | 25/01/2021    | Foundational Concepts | Cartography and Visualisation I | Help/Study Groups | 
| 4             | 01/02/2021    | Foundational Concepts | Programming (for Statistical Analysis) | Seminar |
| 5             | 08/02/2021    | Foundational Concepts | Programming for Spatial Analysis & ESDA | Help/Study Groups |
| **READING WEEK** | **READING WEEK**  | **READING WEEK CODING CHALLENGE** | - | - |
| 6             | 16/11/2021    | Core Spatial Analysis | Analysing Spatial Patterns I: Spatial Auto-Correlation & Regression | Seminar |
| 7             | 23/11/2021    | Core Spatial Analysis | Analysing Spatial Patterns II: Clusters | Help/Study Groups |
| 8             | 30/11/2021    | Core Spatial Analysis | Rasters, Zonal Statistics and Interpolation | Seminar |
| 9             | 07/12/2021    | Advanced Spatial Analysis | Geodemographics | Help/Study Groups |
| 10            | 14/12/2021    | Cartography & Visualisation | Cartography and Visualisation II | Seminar |

The lectures and practicals of this course only form a part of the learning process. You are expected to undertake wider reading (see the Reading List below), particularly to help with your second assessment. 

In addition to our course, there are many other online resources and tutorials that can help expand on the topics and content we cover - whilst it is not necessary for your assessments, you are encouraged to go beyond our recommendations and fully engage with applied GIS research, methods and visualisation techniques. 

Following certain 'movers and shakers' in the GIScience / Spatial Data Science world is one approach to learn more about what's happening in the field and might prove inspirational for your dissertation ideas later this year.

## Reading List {-}

We link to books and resources throughout each practical. The [full reading list for the course](LINK) is provided on the UCL library reading list page for the course. Alternatively, you can always easily find the link to the Reading List in the top right of any Moodle page for our module, under "Library Resources". 

This Reading List will be updated on a weekly basis, in preparation for the week to come, so you may see some weeks without reading for now. But please check back at the **start of each week** as the lecture, seminar and/or workshop material is released for that week to check for new readings. All reading for that week will be provided by the time your learning materials are released - so you will not need to check the reading list for updates as the week progresses.


## Troubleshooting Module Content {-}

Spatial analysis can yield fascinating insights into geographical relationships. However, at times it can be difficult to work with - particularly when we combine this with learning how to program at the same time. You will get lots of error messages and have software crash, you'll end up with bugs in your code that are difficult to find, and you may spend a whole day trying to track down a single dataset. But the rewards of learning how to do all of this (particularly with this year's emphasis on this online research for your dissertations) will become apparent. 

To bring in my first of potentially several cycling references, a well-known quote from Tour De France (1986, 1989, 1990) winner Greg Lemond:

> "It never gets easier, you just go faster."

Resonates quite well with spatial analysis and programming! Even after years of programming, we can still forget the syntax to a `for` loop or question what kernel density estimation actually shows, but you will - by the end of the next ten weeks - know how to find out the answers to these problems faster!

Beyond the help sessions mentioned above, if you need specific assistance with this course please:

* Attend the fortnightly **GIS/coding help sessions** (from Week 3) to ask questions directly to Jakub or Nikki.

* Post in the respective *tech-help* or *r-help* channels within the Geocomputation Team.

* Ask a question at the end of a seminar (time-permitting)

* Check the Moodle assessment tab for queries relating to the assessment (more information will be provided in Week 5)

* Attend the **Coding Therapy sessions** that are run on a weekly basis

Due to the size of the class we will **only reply** to tech and R help messages **on Teams** so all students can see the discussion. If you have a personal matter in relation to completing the course then please speak to or email Jo.

We'd also encourage you to monitor the *tech-help* or *r-help* channels and contribute to/answer questions as/if you can! Creating a small community across our course will help all of us in the long-run.

If after pursuing all these avenues you still need help, you can book into our office hours. These meetings are **to discuss a geographical concept in relation to the material/assessment or for any personal matters relevant to the completion of the module**.

### Additional Online Help & Resources {-}

We are here to help you work through these practicals but even we do not know everything. Therefore, it's a good idea to become familar with online sources of help, such as:

* [Stack Exchange](https://stackexchange.com/)
* [RStudio community](https://community.rstudio.com/)
* [QGIS documemtation](https://docs.qgis.org/3.4/en/docs/index.html)
* [R documentation](https://www.rdocumentation.org/)
* [ArcGIS help pages](https://support.esri.com/en)

Ultimately, if you are struggling to use R don't worry...here is some advice from a tweet and  [interview](https://www.r-bloggers.com/advice-to-young-and-old-programmers-a-conversation-with-hadley-wickham/) with Hadley Wickham, chief scientist at RStudio...

<blockquote class="twitter-tweet tw-align-center"><p lang="en" dir="ltr">You&#39;re doing it right if you get frustrated: if you&#39;re not frustrated, you&#39;re (probably) not stretching yourself mentally</p>&mdash; Hadley Wickham (@hadleywickham) <a href="https://twitter.com/hadleywickham/status/565516733516349441?ref_src=twsrc%5Etfw">11. Februar 2015</a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
<br/>

> It’s easy when you start out programming to get really frustrated and think, “Oh it’s me, I’m really stupid,” or, “I’m not made out to program.” But, that is absolutely not the case. Everyone gets frustrated. I still get frustrated occasionally when writing R code. It’s just a natural part of programming. So, it happens to everyone and gets less and less over time. Don’t blame yourself. Just take a break, do something fun, and then come back and try again later.

We highly advocate taking a break if you get stuck - the Workbook will not disappear, and you can complete the content at your own pace!

:::sds
**Expanding your R learning (to infinity and beyond!)**<br>

In addition to our course, there are many online tutorials that can help with learning R, specifically:

* [Free RStudio Education resources](https://education.rstudio.com)

* [Codeacademy](https://www.codecademy.com/learn/learn-r)

* [YaRrr! The Pirate's Guide to R](https://bookdown.org/ndphillips/YaRrr/)
:::


## Feedback: Weekly and End of Module {-}

We can only make this course better through your feedback. We collect feedback:

* **At the end of every practical.**  There is a link to an anonymous feedback form, please let us know if something is unclear and we will go over it in a future session.

* **At the end of the module.** The standard UCL feedback form will be available to fill in on Moodle.

#### Acknowledgements {-}

Part of this page is adapted from [CASA0005](https://andrewmaclachlan.github.io/CASA0005repo/index.html).