# External Usage  {-}

All the required data to run this course or individual practicals is publicly available through the direct links provided in the practicals. 

For UCL students, access to the Geocomputation Moodle page will enable you to access the pre-formatted datasets, when appropriate.

There are two main options to adopt the written content and practicals of this course:

1. Adopt the course in its entirety by forking the repository on GitHub and Pulling to your local machine or simply download a `.zip` file containing the entire course.

2. Adopt a single practical by downloading the `.rmd` file. 

You will still need to follow the instructions within each practical to download the data - and format it as appropriate. For external users, you are welcome to get in touch with Jo (see previous details)  directly if you would like access to the formatted files or help in how to format them.

## Issues / Contributions {-}

To raise an issue simply log it on the [GitHub issues tab for the repository](https://github.com/jo-wilkin/GEOG0030/issues).

To propose an edit click on the edit symbol in the top tool bar (see [How to use this book]) and submit it for review.

If you wish to contribute material or data then please contact the course convenor Jo Wilkin (details below).

## License {-}

If you use this material for teaching, research or anything else please let me (Andy) know via [Twitter](https://twitter.com/joannawilkin) or email --- j [dot] wilkin [at] ucl [dot] ac [dot] uk).

This practical book is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License](https://creativecommons.org/licenses/by-sa/4.0/).
<center>
<i class="fab fa-creative-commons fa-2x"></i><i class="fab fa-creative-commons-by fa-2x"></i><i class="fab fa-creative-commons-sa fa-2x"></i>
</center>

You are free to: 

* **Share** — copy and redistribute the material in any medium or format

* **Adapt** — remix, transform, and build upon the material
for any purpose, even commercially.

However, you  give appropriate credit, provide a link to the license, and indicate if changes were made. If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

But, you do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.

The code within this pracical book is available under the [MIT license](https://opensource.org/licenses/MIT); so it is free to use (for any purpose) as long as you cite the source.

## Version {-}

This is version 1.0 of the Workbook.

#### Acknowledgements {-}

Part of this page is adapted from [CASA0005](https://andrewmaclachlan.github.io/CASA0005repo/index.html).