<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Programming (for Data Analysis) using R and R-Studio | Geocomputation 2020-2021 Work Book</title>
  <meta name="description" content="GEOG0030: Geocomputation Work Book" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Programming (for Data Analysis) using R and R-Studio | Geocomputation 2020-2021 Work Book" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://jo-wilkin.github.io/GEOG0030/" />
  
  <meta property="og:description" content="GEOG0030: Geocomputation Work Book" />
  <meta name="github-repo" content="jo-wilkin/GEOG0030" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Programming (for Data Analysis) using R and R-Studio | Geocomputation 2020-2021 Work Book" />
  
  <meta name="twitter:description" content="GEOG0030: Geocomputation Work Book" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cartography-and-visualisation-i.html"/>
<link rel="next" href="programming-for-giscience-and-spatial-analysis.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/vembedr-0.1.4/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo">
<a href="https://www.ucl.ac.uk/module-catalogue/modules/geocomputation-GEOG0030"><img src="images/general/ucl-logo.jpg">
</a></li>

<li class="divider"></li>
<li class="part"><span><b>Module Overview</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Module Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#geocomputation-introductory-video"><i class="fa fa-check"></i>Geocomputation Introductory Video</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i>Learning Objectives</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-in-touch-during-the-module"><i class="fa fa-check"></i>Getting in touch during the module</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#noticed-a-mistake-in-this-resource"><i class="fa fa-check"></i>Noticed a mistake in this resource?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html"><i class="fa fa-check"></i>Module Information</a><ul>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#self-guided-learning-for-geocomputation"><i class="fa fa-check"></i>Self-guided learning for Geocomputation</a><ul>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#geocomputation-timetable"><i class="fa fa-check"></i>Geocomputation Timetable</a></li>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#what-will-i-be-learning-each-week"><i class="fa fa-check"></i>What will I be learning each week?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#reading-list"><i class="fa fa-check"></i>Reading List</a></li>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#troubleshooting-module-content"><i class="fa fa-check"></i>Troubleshooting Module Content</a><ul>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#additional-online-help-resources"><i class="fa fa-check"></i>Additional Online Help &amp; Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-information.html"><a href="module-information.html#feedback-weekly-and-end-of-module"><i class="fa fa-check"></i>Feedback: Weekly and End of Module</a></li>
</ul></li>
<li class="part"><span><b>Getting Started</b></span></li>
<li class="chapter" data-level="" data-path="what-is-this-workbook.html"><a href="what-is-this-workbook.html"><i class="fa fa-check"></i>What is this Workbook?</a><ul>
<li class="chapter" data-level="" data-path="what-is-this-workbook.html"><a href="what-is-this-workbook.html#using-this-workbook"><i class="fa fa-check"></i>Using this Workbook</a></li>
<li class="chapter" data-level="" data-path="what-is-this-workbook.html"><a href="what-is-this-workbook.html#workbook-functionality"><i class="fa fa-check"></i>Workbook Functionality</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software Installation</a><ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#qgis"><i class="fa fa-check"></i>QGIS</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-and-r-studio"><i class="fa fa-check"></i>R and R-Studio</a><ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-studio-setup-1"><i class="fa fa-check"></i>R-Studio Setup 1</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-studio-setup-2"><i class="fa fa-check"></i>R-Studio Setup 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#arcgis"><i class="fa fa-check"></i>ArcGIS</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#installation-issues"><i class="fa fa-check"></i>Installation Issues</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="external-usage.html"><a href="external-usage.html"><i class="fa fa-check"></i>External Usage</a><ul>
<li class="chapter" data-level="" data-path="external-usage.html"><a href="external-usage.html#issues-contributions"><i class="fa fa-check"></i>Issues / Contributions</a></li>
<li class="chapter" data-level="" data-path="external-usage.html"><a href="external-usage.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="external-usage.html"><a href="external-usage.html#version"><i class="fa fa-check"></i>Version</a></li>
</ul></li>
<li class="part"><span><b>I Foundational Concepts</b></span></li>
<li class="chapter" data-level="1" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html"><i class="fa fa-check"></i><b>1</b> Geocomputation: An Introduction</a><ul>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#week-1-in-geocomp"><i class="fa fa-check"></i>Week 1 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#what-is-geocomputation"><i class="fa fa-check"></i>What is Geocomputation?</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#giscience-a-short-history"><i class="fa fa-check"></i>GIScience: A Short History</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#spatial-analysis-an-overview"><i class="fa fa-check"></i>Spatial Analysis: An Overview</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#programming-for-data-analysis"><i class="fa fa-check"></i>Programming for Data Analysis</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#whats-next-for-us-in-geocomputation"><i class="fa fa-check"></i>What’s next for us in Geocomputation</a></li>
<li class="chapter" data-level="" data-path="geocomputation-an-introduction.html"><a href="geocomputation-an-introduction.html#getting-ready-for-our-practicals"><i class="fa fa-check"></i>Getting Ready for our Practicals</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html"><i class="fa fa-check"></i><b>2</b> GIScience and GIS software</a><ul>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#week-2-in-geocomp"><i class="fa fa-check"></i>Week 2 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#what-is-representation"><i class="fa fa-check"></i>What is Representation?</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#geographic-representation"><i class="fa fa-check"></i>Geographic Representation</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#spatial-structure-sampling-and-scale"><i class="fa fa-check"></i>Spatial Structure, Sampling and Scale</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#spatial-data-models"><i class="fa fa-check"></i>Spatial Data Models</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#spatial-data-file-formats"><i class="fa fa-check"></i>Spatial Data File Formats</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#gis-software---a-more-thorough-introduction-moved-to-week-5"><i class="fa fa-check"></i>GIS Software - a more thorough introduction (moved to Week 5)</a></li>
<li class="chapter" data-level="" data-path="giscience-and-gis-software.html"><a href="giscience-and-gis-software.html#practical-1-exploring-population-changes-across-london"><i class="fa fa-check"></i>Practical 1: Exploring Population Changes Across London</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html"><i class="fa fa-check"></i><b>3</b> Cartography and Visualisation I</a><ul>
<li class="chapter" data-level="" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html#week-3-in-geocomp"><i class="fa fa-check"></i>Week 3 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html#coordinate-systems-and-map-projections"><i class="fa fa-check"></i>Coordinate Systems and Map Projections</a></li>
<li class="chapter" data-level="" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html#effective-data-visualisation"><i class="fa fa-check"></i>Effective Data Visualisation</a></li>
<li class="chapter" data-level="" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html#the-modifiable-areal-unit-problem"><i class="fa fa-check"></i>The Modifiable Areal Unit Problem</a></li>
<li class="chapter" data-level="" data-path="cartography-and-visualisation-i.html"><a href="cartography-and-visualisation-i.html#practical-2-mapping-crime-across-london-wards-and-boroughs"><i class="fa fa-check"></i>Practical 2: Mapping Crime Across London Wards and Boroughs</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html"><i class="fa fa-check"></i><b>4</b> Programming (for Data Analysis) using R and R-Studio</a><ul>
<li class="chapter" data-level="" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html#week-4-in-geocomp"><i class="fa fa-check"></i>Week 4 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html#an-introduction-to-programming"><i class="fa fa-check"></i>An Introduction to Programming</a></li>
<li class="chapter" data-level="" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html#using-r-and-r-studio-for-data-analysis"><i class="fa fa-check"></i>Using R and R-Studio for Data Analysis</a></li>
<li class="chapter" data-level="" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html#the-tidyverse-philosophy-and-principles"><i class="fa fa-check"></i>The Tidyverse Philosophy and Principles</a></li>
<li class="chapter" data-level="" data-path="programming-for-data-analysis-using-r-and-r-studio.html"><a href="programming-for-data-analysis-using-r-and-r-studio.html#practical-3-analysing-crime-in-2020-in-london"><i class="fa fa-check"></i>Practical 3: Analysing Crime in 2020 in London</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html"><i class="fa fa-check"></i><b>5</b> Programming for GIScience and Spatial Analysis</a><ul>
<li class="chapter" data-level="" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html#week-5-in-geocomp"><i class="fa fa-check"></i>Week 5 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html#spatial-analysis-for-data-science-research"><i class="fa fa-check"></i>Spatial Analysis for Data Science Research</a></li>
<li class="chapter" data-level="" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html#spatial-analysis-software-and-programming"><i class="fa fa-check"></i>Spatial Analysis Software and Programming</a></li>
<li class="chapter" data-level="" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html#spatial-analysis-in-r-studio"><i class="fa fa-check"></i>Spatial Analysis in R-Studio</a></li>
<li class="chapter" data-level="" data-path="programming-for-giscience-and-spatial-analysis.html"><a href="programming-for-giscience-and-spatial-analysis.html#practical-4-analysing-crime-in-2020-in-london-from-a-spatial-perspective"><i class="fa fa-check"></i>Practical 4: Analysing Crime in 2020 in London from a spatial perspective</a></li>
</ul></li>
<li class="part"><span><b>II Core Spatial Analysis</b></span></li>
<li class="chapter" data-level="6" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><i class="fa fa-check"></i><b>6</b> Analysing Spatial Patterns I: Spatial Auto-Correlation &amp; Regression</a><ul>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#week-6-in-geocomp"><i class="fa fa-check"></i>Week 6 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#workshop-housekeeping"><i class="fa fa-check"></i>Workshop Housekeeping</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#analysing-spatial-patterns"><i class="fa fa-check"></i>Analysing Spatial Patterns</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#analysing-distributions"><i class="fa fa-check"></i>Analysing Distributions</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#spatial-autocorrelation-and-clustering-analysis"><i class="fa fa-check"></i>Spatial Autocorrelation and Clustering Analysis</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#analysing-spatial-autocorrelation-in-childhood-obesity-and-deprivation-in-london-wards"><i class="fa fa-check"></i>Analysing Spatial Autocorrelation in Childhood Obesity and Deprivation in London Wards</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#analysing-relationships"><i class="fa fa-check"></i>Analysing Relationships</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html"><a href="analysing-spatial-patterns-i-spatial-auto-correlation-regression.html#recap---analysing-spatial-patterns-i-spatial-auto-correlation-regression"><i class="fa fa-check"></i>Recap - Analysing Spatial Patterns I: Spatial Auto-Correlation &amp; Regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><i class="fa fa-check"></i><b>7</b> Analysing Spatial Patterns II: Geometric Operations &amp; Spatial Queries</a><ul>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#week-7-in-geocomp"><i class="fa fa-check"></i>Week 7 in Geocomp</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#workshop-housekeeping-1"><i class="fa fa-check"></i>Workshop Housekeeping</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#geometric-operations-spatial-queries"><i class="fa fa-check"></i>Geometric Operations &amp; Spatial Queries</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#geometric-operations-spatial-queries-in-action"><i class="fa fa-check"></i>Geometric Operations &amp; Spatial Queries In Action</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#practical-6---part-one-geometric-operations-spatial-queries-approaches"><i class="fa fa-check"></i>Practical 6 - Part One: Geometric Operations &amp; Spatial Queries Approaches</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#practical-6---part-two-analysing-and-visualising-point-data"><i class="fa fa-check"></i>Practical 6 - Part Two: Analysing and Visualising Point Data</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#extension-using-spatial-queries-to-calculate-the-number-of-bike-thefts-within-400m-of-each-station"><i class="fa fa-check"></i>Extension: Using spatial queries to calculate the number of bike thefts within 400m of each station</a></li>
<li class="chapter" data-level="" data-path="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html"><a href="analysing-spatial-patterns-ii-geometric-operations-spatial-queries.html#recap---analysing-spatial-patterns-ii-geometric-operations-and-spatial-operations"><i class="fa fa-check"></i>Recap - Analysing Spatial Patterns II: Geometric Operations and Spatial Operations</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysing-spatial-patterns-iii-point-pattern-analysis.html"><a href="analysing-spatial-patterns-iii-point-pattern-analysis.html"><i class="fa fa-check"></i><b>8</b> Analysing Spatial Patterns III: Point Pattern Analysis</a></li>
<li class="chapter" data-level="9" data-path="rasters-zonal-statistics-and-interpolation.html"><a href="rasters-zonal-statistics-and-interpolation.html"><i class="fa fa-check"></i><b>9</b> Rasters, Zonal Statistics and Interpolation</a></li>
<li class="part"><span><b>III Advanced Spatial Analysis</b></span></li>
<li class="chapter" data-level="10" data-path="geodemographic-classification.html"><a href="geodemographic-classification.html"><i class="fa fa-check"></i><b>10</b> Geodemographic Classification</a></li>
<li class="chapter" data-level="11" data-path="spatial-regression-models-optional.html"><a href="spatial-regression-models-optional.html"><i class="fa fa-check"></i><b>11</b> Spatial Regression Models (Optional)</a></li>
<li class="chapter" data-level="12" data-path="accessibility-network-analysis-optional.html"><a href="accessibility-network-analysis-optional.html"><i class="fa fa-check"></i><b>12</b> Accessibility &amp; Network Analysis (Optional)</a></li>
<li class="chapter" data-level="13" data-path="for-loops-and-functions-for-automated-data-processing-visualisation-optional.html"><a href="for-loops-and-functions-for-automated-data-processing-visualisation-optional.html"><i class="fa fa-check"></i><b>13</b> For Loops and Functions for Automated Data Processing &amp; Visualisation (Optional)</a></li>
<li class="part"><span><b>Assessment</b></span></li>
<li class="chapter" data-level="" data-path="assessment-information.html"><a href="assessment-information.html"><i class="fa fa-check"></i>Assessment Information</a><ul>
<li class="chapter" data-level="" data-path="assessment-information.html"><a href="assessment-information.html#useful-additional-resources"><i class="fa fa-check"></i>Useful additional resources</a></li>
</ul></li>
<li class="part"><span><b>Dissertation Help</b></span></li>
<li class="chapter" data-level="" data-path="extra-resources-for-help-with-quantitative-dissertations.html"><a href="extra-resources-for-help-with-quantitative-dissertations.html"><i class="fa fa-check"></i>Extra resources for help with Quantitative Dissertations</a><ul>
<li class="chapter" data-level="" data-path="extra-resources-for-help-with-quantitative-dissertations.html"><a href="extra-resources-for-help-with-quantitative-dissertations.html#video-guidance-on-quantitative-dissertations"><i class="fa fa-check"></i>Video Guidance on Quantitative Dissertations</a></li>
<li class="chapter" data-level="" data-path="extra-resources-for-help-with-quantitative-dissertations.html"><a href="extra-resources-for-help-with-quantitative-dissertations.html#dataset-guidance"><i class="fa fa-check"></i>Dataset Guidance</a></li>
</ul></li>
<li class="part"><span><b>Alternate Tutorials</b></span></li>
<li class="chapter" data-level="" data-path="week-2-practical-alternate-using-agol-for-population-mapping.html"><a href="week-2-practical-alternate-using-agol-for-population-mapping.html"><i class="fa fa-check"></i>Week 2 Practical Alternate: Using AGOL for Population Mapping</a><ul>
<li class="chapter" data-level="" data-path="week-2-practical-alternate-using-agol-for-population-mapping.html"><a href="week-2-practical-alternate-using-agol-for-population-mapping.html#a-short-introduction-to-arcgis-online"><i class="fa fa-check"></i>A short introduction to ArcGIS Online</a></li>
<li class="chapter" data-level="" data-path="week-2-practical-alternate-using-agol-for-population-mapping.html"><a href="week-2-practical-alternate-using-agol-for-population-mapping.html#sign-up-to-arcgis-online"><i class="fa fa-check"></i>Sign Up to ArcGIS Online</a></li>
<li class="chapter" data-level="" data-path="week-2-practical-alternate-using-agol-for-population-mapping.html"><a href="week-2-practical-alternate-using-agol-for-population-mapping.html#practical-instructions"><i class="fa fa-check"></i>Practical Instructions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="week-3-practical-alternate-using-agol-for-crime-mapping.html"><a href="week-3-practical-alternate-using-agol-for-crime-mapping.html"><i class="fa fa-check"></i>Week 3 Practical Alternate: Using AGOL for Crime Mapping</a><ul>
<li class="chapter" data-level="" data-path="week-3-practical-alternate-using-agol-for-crime-mapping.html"><a href="week-3-practical-alternate-using-agol-for-crime-mapping.html#practical-instructions-1"><i class="fa fa-check"></i>Practical Instructions</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Geocomputation 2020-2021 Work Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<link href="style.css" rel="stylesheet">
<div class="hero-image-container"> 
  <img class= "hero-image" src="../images/general/overview.png">
</div>
<div id="programming-for-data-analysis-using-r-and-r-studio" class="section level1">
<h1><span class="header-section-number">4</span> Programming (for Data Analysis) using R and R-Studio</h1>
<p>Welcome to Week 4 in Geocomputation!</p>
<p>Well done on making it through Week 3 - and welcome to our introduction to using programming, in the form of R and R-Studio, for data analysis.</p>
<p>This week is heavily practical oriented - with <strong>many aspects of your practical integrated at various points in the workshop</strong> - as well as, of course, a data analysis section towards the end.</p>
<p>As always, we have broken the content into smaller chunks to help you take breaks and come back to it as and when you can over the next week.</p>
<div id="week-4-in-geocomp" class="section level3 unnumbered">
<h3>Week 4 in Geocomp</h3>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/12b10df4-0f35-45bc-b96a-555f6d322d4f?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://web.microsoftstream.com/video/12b10df4-0f35-45bc-b96a-555f6d322d4f">Video on Stream</a>
</center>
<p><br></p>
<p>This week’s content introduces you to the foundational concepts associated with <strong>Programming for Data Analysis</strong>, where we have three areas of work to focus on:</p>
<ol style="list-style-type: decimal">
<li>General principles of programming</li>
<li>How to use R and R-Studio effectively for programmatical data analysis</li>
<li>The ‘Tidyverse’ philosophy</li>
</ol>
<p>This week’s content is split into <strong>4</strong> parts:</p>
<ol style="list-style-type: decimal">
<li><a href="programming-for-data-analysis-using-r-and-r-studio.html#an-introduction-to-programming">An Introduction to Programming</a> (40 minutes)</li>
<li><a href="programming-for-data-analysis-using-r-and-r-studio.html#using-r-and-r-studio-for-data-analysis">Using R and R-Studio for Data Analysis</a> (60 minutes)</li>
<li><a href="programming-for-data-analysis-using-r-and-r-studio.html#the-tidyverse-philosophy-and-principles">The Tidyverse Philosophy and Principles</a> (40 minutes)</li>
<li><a href="programming-for-data-analysis-using-r-and-r-studio.html#practical-3-analysing-crime-in-2020-in-london">Practical 3: Analysing Crime in 2020 in London</a> (30 minutes)</li>
</ol>
<p>This week, we have a slightly different approach to our workflow structure, with a mixture of <strong>short lectures</strong>, <strong>instructional videos</strong> and <strong>activities</strong> to complete throughout each part.</p>
<p>A single <strong>Key Reading</strong> is found towards the end of the workshop.</p>
<p>This week, you have <strong>1 assignment</strong>, which will be highlighted in the workbook.</p>
<p><strong>Part 4</strong> is the main part of analysis for our Practical for this week, but you will find aspects of programming in <strong>Parts 1-3</strong> that you will need to do in order <strong>to prepare our data for the final part</strong>.</p>
<p>If you have been unable to download R-Studio Desktop or cannot access it via Desktop@UCL Anywhere, you will have access to our R-Studio Server website instead. Instructions on how to access this are provided below.</p>
<div class="puzzle">
<p><strong>Learning Objectives</strong><br><br>
By the end of this week, you should be able to:</p>
<ul>
<li>Understand the basics of programming and why it is useful for data analysis</li>
<li>Recognise the differences and purpose of a console command versus the creation of a script</li>
<li>Explain what a library/package is and how to use them in R/R-Studio</li>
<li>Explain the tidyverse philosophy and why it is useful for us as data analysts</li>
<li>Wrangle and manage tabular data to prepare it for analysis</li>
<li>Conduct basic descriptive statistics using R-Studio and R and produce a bar chart</li>
</ul>
</div>
<p>We will build on the data analysis we completed last week and look to further understand crime in London by looking at its prevalence on a month-by-month basis.</p>
<hr />
</div>
<div id="an-introduction-to-programming" class="section level3 unnumbered">
<h3>An Introduction to Programming</h3>
<p>Programming is our most fundamental way of interacting with a computer - it was how computers were first built and operated - and for a <strong>long</strong> time, the Command Line Interface (CLI) was our primary way of using computers before our Graphical User Interface (GUI) Operating Systems (OS) and software became mainstream.</p>
<p>Nowadays, the majority of us use our computers through clicking - and not typing. However, programming and computer code underpin every single application that we use on our computers… or really any technological device.</p>
<p>After all, programming is used for so many purposes and applications, that, we as users take for granted - from software engineering and application development, to creating websites and managing databases at substantial scales.</p>
<p>To help with this diversity of applications, multiple types of programming languages (and ways of using programming languages!) have developed - Wikipedia, for example, has a list of <strong>50 different types</strong> of languages, although there is some overlap between many of these and some are used for incredibly niche activties.</p>
<p>In general, the main programming languages that people focus on learning at the moment include:</p>
<img src="images/w4/04_programming_languages.png" width="850pt" style="display: block; margin: auto;" />
<br>
<center>
<em>Top 10 programming languages and their applications according to DZone in 2017.</em>
</center>
<p><br></p>
<p>Some can be used for a range of purposes – others are more specific, e.g. HTML for website building. There are also different ways in which programming languages work, which give some advantages over others.</p>
<p>This is to do with how the code is written and ‘talks to the computer’ - behind our main programming languages there is something called a compiler that takes the code we write in our various programming languages and translates it into machine code, a.k.a. the code our computers know how to understand.</p>
<p>This code is written purely in binary and, as a result, looks <strong>a lot</strong> different to the code we’ll be writing in our practicals (think a lot of 1s and 0s!).</p>
<p>For some languages, this translation is completed when your code is compiled before it is run, i.e. the ‘compiler’ will look through all your code, translate to machine code and then execute the machine code according.</p>
<p>These languages are known as <strong>compiled</strong>, or <strong>low-level</strong> languages and can, at first, be slow to write but are incredibly efficient when executing huge amounts of code (e.g. when creating software). They however require an understanding of things called registers, memory addresses, and call stacks and are, as a result, a lot more complicated to learn and use (and no, I personally do not know how to code in any low-level languages…nor do I particularly want to!).</p>
<p>For other languages, such as R and Python, these fall into the <strong>interpreted</strong> language category. Here, each line of code is executed without a pre-runtime translation. In this case, a program called an interpreter reads each program statement and, following the program flow, then decides what to do, and does it.</p>
<p>The issue with these <strong>high-level</strong> programming languages is that this approach can be costly in computational resources (i.e. processing time and memory space).</p>
<p>As there is no pre-run time compilation, bugs are not found before the code is run but instead as the code is run - as a result (and what you might see happen in your own code), your computer can get stuck trying to execute code which is either completely unfeasible for your computer to execute (e.g. your computer cannot handle the size of data you are feeding it) or it ends up in a loop with no way out - except for you stopping the code.</p>
<p>However, the advantage of using these languages is that their main focus is on things like variables, arrays, objects, complex arithmetic or boolean expressions, subroutines and functions, loops, threads, locks, and other abstract computer science concepts - all of which we’ll use within our module, believe it or not!</p>
These languages have a primary focus on usability over optimal program efficiency, which, when we’re just learning to code, are ideal for us in Geocomputation!
<br><br>
<center>
<em>Don’t worry if you don’t understand what any of this means, you will do by the end of this module!</em>
</center>
<p><br></p>
<p>As we’re not taking a Computer Science degree here, we won’t go into any more detail about this, but suffice to say, there is a lot more to programming then what we’ll cover in Geocomputation.</p>
<p>But what is important to recognise is that <strong>a lot</strong> of work went into creating the programming environments that we get to use today - and I, for one, am extremely glad I never had to learn how to write a compiler!</p>
<p>If understanding a little more about compilers and machine code is of interest to you, the below video provides an accessible explanation - although you might want to come back to it at the end of the practical:</p>
<center>
<strong>How do computers read code?</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/QXjU9qTsYCc" width="533" height="300" frameborder="0" allowfullscreen=""></iframe>
</div>
</div>
<div id="the-command-line-interface" class="section level4 unnumbered">
<h4>The Command Line Interface</h4>
<p>The most basic of programming we can use without installing anything on our computers is using the <strong>Command Line Interface</strong>(CLI) already built in, known as the <strong>shell</strong>.</p>
<p>The <strong>shell</strong> is a simple program that lets you interact with your computer using text commands (Command Line Interface) instead of a point &amp; click <strong>Graphical User Interface</strong> (GLI).</p>
<p>The shell simply takes your commands and provides them to the operating system of your computer.</p>
<p>Each operating system has its own shell program:</p>
<ul>
<li><p><strong>Mac / Linux</strong> = <strong>zsh</strong> (new) / <strong>bash</strong> (Bourne-again Shell) (previous)</p></li>
<li><p><strong>Microsoft</strong> = <strong>PowerShell</strong> (and a few others).</p></li>
</ul>
<p>For most operating systems, you can access the shell using a window-based program, known as a <strong>terminal emulator (TE)</strong>.</p>
<ul>
<li><p>The default <strong>TE</strong> for <strong>Mac &amp; Linux</strong> users is: <strong>Terminal</strong>.</p></li>
<li><p>The default <strong>TE</strong> for <strong>Windows</strong> users use <strong>Command Prompt</strong> (old) or <strong>Terminal</strong> (new).</p></li>
</ul>
<p><em>(If you remember my introductory lecture, this is how I used to have to interact with my first computer at a very young age of probably 5 when attempting to load a computer game!)</em></p>
<p>The <strong>shell</strong> is an incredibly useful program - and if you take programming further in the future (e.g. analysis of big datsets through servers, running multiple scripts, dealing with version control, software engineering), it will become a tool that you’ll become incredibly familiar with.</p>
<p>But for now, we just want to illustrate how cool it can be for us to be able to tell our computer to do things in a few lines of code - rather than having to click and point - particularly once you know how to use the CLI-shell and can remember specific commands.</p>
<p>Let’s take a look by completing a simple task with our shell to tell our computer to do something - let’s do some <strong>file management</strong> for our practical today.</p>
<div id="using-the-command-line-interface-on-your-computer" class="section level5 unnumbered">
<h5>Using the Command Line Interface On Your Computer</h5>
<p>As you may remember from last week’s practical, I provided you with our crime data in a single processed csv file.</p>
<p>However, when you download the data from <strong>data.police.uk</strong>, the data is not so nicely formatted!</p>
<p>Essentially, all of our data that we download for crime in London will be provided in individual csvs, according first to month, and then to the police force as so:</p>
<p><img src="images/w3/crime_data_files.png" width="650pt" style="display: block; margin: auto;" /></p>
<p>To be able process this data easily in R, we want to move all of our files into a single folder.</p>
<p>And believe it or not, it only takes a couple of lines of code to do so.</p>
<p>Let’s take a look:</p>
<center>
<strong>Using the Command Line to copy and move files.</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/4a2c7bde-4074-4307-90d4-19ad73eef9f9?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://web.microsoftstream.com/video/4a2c7bde-4074-4307-90d4-19ad73eef9f9">Video on Stream</a>
</center>
<p><br></p>
<p>As we’ve seen in the video above, it can really useful - and quick - to use our Shell to organise our data files prior to loading them in R-Studio.</p>
<p>Just to proove this, the first piece of programming we will do today is use your built-in shell on your computer to repeat the same process and copy our crime data into a single folder.</p>
</div>
</div>
<div id="file-management-using-the-command-line" class="section level4 unnumbered">
<h4>File Management using the Command Line</h4>
<p>Now you’ve watched how I copy the files over, let’s go ahead and do this ourselves.</p>
<ol style="list-style-type: decimal">
<li>Head to <strong>data.police.uk</strong> and download all available crime data for London in 2020 (this may only include up until November) and for both Police Forces.</li>
</ol>
<center>
<em>The below video shows you how to do this.</em>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/5143010c-bf7a-47b9-b7ec-a74ef1834615?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<p>You should now have your data downloaded in a single main folder in your downloads (it may be given a ridiculously long coded filename).</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Copy this folder into your <strong>GEOG0030 -&gt; data -&gt; raw -&gt; crime</strong> folder using copy and paste / drag-drop (whatever your preference).</p></li>
<li>Next, open up your shell on your computer.
<ul>
<li>On <strong>mac</strong>, hold <strong>CMD</strong> and hit <strong>space</strong> to open up your search bar and type <strong>terminal</strong>, and a terminal window should appear.</li>
<li>On <strong>windows</strong>, press the windows button and do the same. Alternatively search for <strong>shell</strong> or <strong>command prompt</strong>.</li>
</ul></li>
</ol>
<p>With your shell open, we will navigate to your raw data folder and copy over the crime data into a single folder.</p>
<p>To do so, we’ll use six main terminal commands:</p>
<div class="codetime">
<p><strong>Common Shell/Terminal Commands</strong><br></p>
<ul>
<li><strong>pwd</strong> (both Mac and Windows): <strong>Print Working Directory</strong> - this will show us where we are in our computer’s file system. By default, you should be located at the “base” of your user file.</li>
<li><strong>dir</strong> (Windows) or <strong>ls</strong> (Mac): <strong>Lists</strong> all files in the directory you are currently located.</li>
<li><strong>cd</strong> (both Mac and Windows): <strong>Change</strong> into a new <strong>directory</strong> (i.e. folder) - this can be a single path ‘step’ or several steps to get to the directory you want.</li>
<li><strong>md</strong> (Windows) or <strong>mkdir</strong> (both Mac and Windows): <strong>Make</strong> a new <strong>directory</strong> (i.e. folder) where you are currently located.</li>
<li><strong>cp</strong> (both Mac and Windows): <strong>Copy</strong> content of a directory or specific file to a new location. This command can take <strong>wildcards</strong> to help search multiple folders at once, as we’ll see in our query.</li>
<li><strong>move</strong> (Windows) or <strong>mv</strong> (Mac): <strong>Move</strong> directory to a new destination.</li>
</ul>
</div>
<p>Let’s get going.</p>
<ol start="4" style="list-style-type: decimal">
<li>In your shell, type the command <code>pwd</code> and press return.</li>
</ol>
<p>You should now see a file path appear under your command - the computer is telling you where you are currently located in your computer system.</p>
<ol start="5" style="list-style-type: decimal">
<li>Next, type <code>dir</code> OR <code>ls</code> (OS-dependent) and press return.</li>
</ol>
<p>The computer now lists all of the folders in your directory that you can move into as a next step from your current folder.</p>
<br>
<center>
<strong>You now need to identify what folder your GEOG0030 work is contained in - and what your “path” is to get there as we now need to continue changing directories to get to our GEOG0030 folder.</strong>
</center>
<p><br></p>
<ol start="6" style="list-style-type: decimal">
<li>Next, type <code>cd</code> followed by the folder(s) you need to change into in order to get to your main <code>GEOG0030</code> folder. Remember to press return to execute your code.</li>
</ol>
<center>
In my case, the command is: <code>cd Code</code>.
</center>
<p>Each time you change folder, this folder is added to the file path next to your <strong>Prompt</strong> - have a quick look at this now.</p>
<p>Keep going changing folders until you are in the folder that contains your downloaded crime data.</p>
<div class="codetime">
<p><strong>Auto-Population of File Paths</strong><br></p>
<p><strong>A tip is that your terminal can auto-populate your folder names for you when there is enough information for them to determine the unique folder. To do this, press <code>tab</code> on your keyboard.</strong></p>
<p>E.g. your crime folder is likely to be a long list of numbers and letters if you haven’t renamed it whilst copying it over to your raw folder. Therefore I recommend using this approach will save you time entering all these numbers.</p>
<p>You can also change into this folder in one command, simply keep adding to your folder path as so:</p>
<ul>
<li>Type in (and use tab) <code>cd GEOG0030/data/raw/crime/52c6b758bceaf2244fc1b6f93e85d7f00f234ccf/</code> and then press return.
<ul>
<li>Note, if you are using a WINDOWS PC, you need to use a backslash (\) in your file path, not a forward-slash.</li>
<li>Note, you do not need a slash at the start of your file paths.*</li>
</ul></li>
</ul>
</div>
<p>Once you are in the correct folder, we first want to make a <strong>new folder</strong> to contain <strong>all</strong> the crime csvs (without their current subfolder system):</p>
<ol start="8" style="list-style-type: decimal">
<li>Type in <code>mkdir all_crime</code> and press return.</li>
</ol>
<p>If you now type <code>dir</code> or <code>ls</code>, you should now see the new folder listed within your current folder.</p>
<p>Let’s go ahead and copy all of our csvs into this single folder.</p>
<ol start="9" style="list-style-type: decimal">
<li>Type <code>cp **/*.csv all_crime</code> and press return.
<ul>
<li>Again use a backslash ()) if on a Windows PC.</li>
<li>This command uses the <strong>wildcard * </strong> to search for any file in any folder, as long as it has a <code>.csv</code> file type.</li>
<li>Using <strong>wildcards</strong> is a very common programming tool and we are likely to use them in our practicals moving forward. You can also use them in searches on search engines such as Google!</li>
</ul></li>
</ol>
<p>We can now change into our new folder and then list its contents to check that our files have moved across.</p>
<ol start="10" style="list-style-type: decimal">
<li>Type <code>cd all_crime</code> and press return. Then type <code>dir</code> or <code>ls</code>. Check that you have all your files (either 22 or 24, depending on when you are completing this practical!).</li>
</ol>
<p>Great, we have our files all in a single folder which will make using them in R much easier. We’ll do one final thing - and that is move this folder out of this original and into the main <code>crime</code> folder.</p>
<ol start="11" style="list-style-type: decimal">
<li><p>Still in the terminal, type: <code>cd ..</code> to take a step back into our police crime data folder.</p></li>
<li><p>Next, to move our <code>all_crime</code> folder: (WINDOWS) <code>move all_crime ..</code> or (MAC): <code>mv all_crime ..</code></p></li>
<li><p>Finally, type <code>cd ..</code> and press return.</p></li>
</ol>
<p>You should now find yourself <strong>one step</strong> back in your file system in the main crime folder. We can check that our move worked by again listing the contents of the folder.</p>
<ol start="14" style="list-style-type: decimal">
<li>Type <code>dir</code> or <code>ls</code> and press return. Check that your <code>all_crime</code> folder is now listed.
:::</li>
</ol>
<p>Great! You’ve just done your first bit of command line programming!</p>
<p>Think about how quick was it to type those commands and get the files moved - rather than have to do all of that by hand.</p>
<p>Of course it helped that I told you what commands to write - but the more time you spend with programming, the quicker (and more familiar) you will get at (with) coding and executing these commands.</p>
<div class="note">
<p><strong>Command Line Paths</strong><br></p>
<p>Note, the use of <code>..</code> in our two commands above means to take a step back in your file system path, as we did in both of these cases here (i.e. the ‘parent’ folder.</p>
<p>In addition, two further commands to be aware of include:</p>
<ul>
<li><code>~</code> (Mac) to denote the <strong>root</strong> or <strong>home</strong> directory, e.g. <code>cd ~</code>.
<ul>
<li>In Windows, there is not really a shortcut for this.</li>
</ul></li>
<li><code>.</code>: a single full-stop means “this folder”.</li>
</ul>
</div>
<p>The command line is just one aspect of programming - but we also want to have the ability to create and run scripts.</p>
<p>Scripts are incredibily important for us when completing data anlaysis and, as such, we’ll look at the differences between the two as we start to use R/R-Studio for our data analysis today.</p>
<p>One cool thing about the terminal is that we actually have the ability to create and run scripts just within the terminal itself.</p>
<p>We can do this by opening up a <strong>text editor</strong> in our terminal to write a script in any programming language and then execute our script within the terminal. We execute our script by actually setting the terminal to that programming language and then calling the script.</p>
<p>This all sounds extremely complicated - but it really is not once you’ve spent a bit of time working with the CLI.</p>
<p>We can have a quick look here:</p>
<center>
<strong>Using the Command Line to create and run scripts (in Python).</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/c1bc80a0-da79-4add-aeac-d15a5c8d1e29?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://web.microsoftstream.com/video/c1bc80a0-da79-4add-aeac-d15a5c8d1e29">Video on Stream</a>
</center>
<p><br></p>
<p>Whilst we could use this type of approach for data analysis for conducting actual spatial analysis, we won’t be doing so in Geocomptuation (you are probably happy to read!).</p>
<p>This is because, quite frankly, the terminal is pretty limited in its display of maps and charts, a key output of our work here in Geocomputation, and general user-friendly functionality. In fact, we’d need to save our outputs to a file each time to go view them, which would end up being a pretty clunky workflow…</p>
<p>Instead, what’s great is that we have several different types of software and Integrated Develoement Environments that bring the functionality of running scripts together with the visualisation capacity we like in our GIS software.</p>
<p>For us in Geocomputation, our tool of choice for this is <strong>R-Studio</strong>.</p>
</div>
</div>
<div id="using-r-and-r-studio-for-data-analysis" class="section level3 unnumbered">
<h3>Using R and R-Studio for Data Analysis</h3>
<p>Before we go any further, what I want to make clear from this workshop - and the remainder of the module - is that programming using R and R-Studio is ultimately a <strong>tool</strong> we will use to complete specific tasks we need to do for our data analysis.</p>
<p>There are <strong>a lot</strong> of different tools out there that you can use to achieve the same outcomes (as you’ve seen with Q-GIS, and no doubt had experience of using some statistics/spreadsheet software) but we choose to use this tool because it provides us with many advantages over these other tools - more on this next week.</p>
<p>With this <strong>tool</strong> though, there is a lot to learn about the <strong>principles and the theory behind programming languages</strong>.</p>
<p>As evident above, whilst we could look at this in a lot of detail (there is <em>a lot</em> of theory behind programming which we just won’t cover - that’s for computer scientists), we will instead focus on the <strong>aspects</strong> most important to our use, which is covered in our main lecture video below: <strong>Principles of Programming for Data Analysis</strong> in the <a href="programming-for-data-analysis-using-r-and-r-studio.html#programming-for-data-analysis-1">Programming for Data Analysis</a> section.</p>
<p>The second thing to make clear is that <strong>R</strong> and <strong>R-Studio</strong> are two different things:</p>
<p><img src="images/w4/r-logo.jpg" width="200pt" style="display: block; margin: auto;" /></p>
<center>
<strong>R</strong> is our programming language, which we need to understand in terms of <strong>general principles</strong>, <strong>syntax</strong> and <strong>structure</strong>.
</center>
<p><br></p>
<p><img src="images/w4/RStudio-Logo-Flat.png" width="350pt" style="display: block; margin: auto;" /></p>
<center>
<strong>R-Studio</strong> is our <strong>Integrated Development Environment</strong>, which we need to understand in terms of <strong>functionality</strong> and <strong>workflow</strong>.
</center>
<p><br></p>
<div class="fyi">
<p><strong>Integrated Development Environment</strong><br>
An Integrated Development Environment (IDE) is simply a complicated way of saying “a place where I write and build scripts and execute my code”.</p>
<p>Nowadays, we have some really fancy IDEs that, when they know what language you are coding in, will highlight different types of code according to what they represent (e.g. a variable, a function) as well as try to proof-read/de-bug your code “on-the-fly” before you’ve even run it.</p>
<p>R-Studio is definitely a <strong>very</strong> fancy IDE - as it offers <strong>a lot</strong> of functionality beyond just writing scripts and execute code as we’ll see over the coming weeks.</p>
</div>
<p>As you may know already, <a href="https://www.r-project.org/">R</a> is a free and open-source programming language, that originally was created to focus on statistical analysis.</p>
<p>In conjunction with the development of <strong>R</strong> as a language, the same community created the <strong>R-Studio</strong> <strong>IDE</strong> (or really software now!) to execute this statisitcal programming.</p>
<p>Together, <strong>R</strong> and <strong>R-Studio</strong> has grown into an incredibly success partnership of analytical programming language and analysis software - and is widely used for academic research as well as in the commercial sector.</p>
<p>One of R’s great strength is that it is open-source, can be used on all major computer operating systems and is free for anyone to use. It, as a result, has a huge and active contributor community which constantly adds functionality to the language and software, making it an incredibly useful tool for many purposes and applications beyond statistical analysis.</p>
<div class="note">
<p><strong>Believe it or not, the entire workbook you are reading right now has been created in R-Studio</strong>, utilising a mixture of programming languages, including R, HTML, CSS and Markdown.</p>
</div>
<p>R-Studio has the <strong>flexibility</strong> to understand programming languages other than <strong>R</strong> (including Python!), whilst <strong>R</strong> can be deployed outside of the <strong>R-Studio</strong> environment in standalone scripts and other IDEs.</p>
<p>However, for us, the partnership between R and R-Studio works pretty well for what we want to achieve - so this is what we’ll be using for the remainder of the Geocomputation module.</p>
<div id="how-do-i-use-r-studio" class="section level4 unnumbered">
<h4>How do I use R-Studio?</h4>
<p>Unlike traditional statistical analysis programmes you may have used such as <strong>Microsoft Excel</strong> or even <strong>SPSS</strong>, within the R-Studio IDE, the user has to type commands to get it to execute tasks such as loading in a dataset or performing a calculation.</p>
<p>We primarily do this by building up a script (or similar document, more on this in Week 10), that provides a record of what you have done, whilst also enabling the straightforward repetition of tasks.</p>
<p>We can also use the <strong>R Console</strong> to execute simple instructions that do not need repeating - such as installing libraries or quickly viewing data (we’ll get to this in a second).</p>
<p>In addition, R, its various graphic-oriented “packages” and R-Studio are capable of making graphs, charts and maps through just a few lines of code (you might notice a <strong>Plots</strong> window to your right in your R-Studio window) - which can then be easily modified and tweaked by making slight changes to the script if mistakes are spotted.</p>
<p>Unfortunately, command-line computing can also be off-putting at first. It is easy to make mistakes that are not always obvious to detect and thus debug.</p>
<p>Nevertheless, there are good reasons to stick with R and R-Studio.</p>
<p>These include:</p>
<ul>
<li><p>It is broadly intuitive with a strong focus on publishable-quality graphics.</p></li>
<li><p>It is ‘intelligent’ and offers in-built good practice – it tends to stick to statistical conventions and present data in sensible ways.</p></li>
<li><p>It is <strong>free</strong>, cross-platform, customisable and extendable with a whole swathe of packages/libraries (‘add ons’) including those for discrete choice, multilevel and longitudinal regression, and mapping, spatial statistics, spatial regression, and geostatistics.</p></li>
<li><p>It is well respected and used at the world’s largest technology companies (including Google, Microsoft and Facebook, and at hundreds of other companies).</p></li>
<li><p>It offers a <strong>transferable skill</strong> that shows to potential employers experience both of statistics and of computing.</p></li>
</ul>
<p>The intention of the practical elements of this week is to provide a thorough introduction to R-Studio to get you started:</p>
<p><strong>1. The basic programming principles behind R.</strong></p>
<p><strong>2. Loading in data from <code>csv</code> files, filtering and subsetting it into smaller chunks and joining them together.</strong></p>
<p><strong>3. Calculating a number of statistics for data exploration and checking.</strong></p>
<p><strong>4. Creating basic and more complex plots in order to visualise the distributions values within a dataset.</strong></p>
<p>What you should remember is that R/R-Studio has a steep learning curve, but the benefits of using it are well worth the effort.</p>
<p>I highly recommend you take your time and think through every piece of code you type in - and also remember to comment your code (we’ll get to this in a bit!) .</p>
<p>The best way to learn R is to take the basic code provided in tutorials and experiment with changing parameters - such as the colour of points in a graph - to really get ‘under the hood’ of the software.</p>
<p>Take lots of notes as you go along and if you are getting really frustrated take a break!</p>
<p>This week, we focus solely on using R and R-Studio (from now on, this may be simply denoted as R) for <strong>basic statistical data analysis</strong>.</p>
<p>Next week, we will introduce using R for <strong>spatial (data) analysis</strong> - but there’s lots to get on with today to understand the fundamental principles of using R (and programming in general).</p>
</div>
<div id="accessing-r-studio-for-geocomputation" class="section level4 unnumbered">
<h4>Accessing R-Studio for Geocomputation</h4>
<p>You have two options for using R-Studio in this module.</p>
<ol style="list-style-type: decimal">
<li><p>Using <strong>R-Studio Desktop</strong>: You should have installed this in Week 1 as per the software installation instructions.</p></li>
<li>Using <strong>R-Studio Server</strong>:
<ul>
<li>First sign in to the UCL VPN or UCL China Connect.</li>
<li>To use R-Studio Server, open a web browser and navigate to: <a href="https://rstudio.data-science.rc.ucl.ac.uk/" class="uri">https://rstudio.data-science.rc.ucl.ac.uk/</a></li>
<li>Log in with your <strong>usual UCL username and password</strong>.</li>
<li>You should see the RStudio interface appear.</li>
<li>If it is the first time you log on to RStudio server you may only see the RStudio interface appear once you have clicked on the <strong>start a new session</strong> button.</li>
</ul></li>
</ol>
<p>You can use either approach - but do recognise their may be some differences oh how our code appears.</p>
<p>The code below has been created on an R-Studio Desktop Version 1.2.5033 and tested on the R-Studio Server.</p>
<div class="note">
<p><strong>Note</strong><br></p>
<p>RStudio server will only work with an <a href="https://www.ucl.ac.uk/isd/it-essentials-for-new-students/video-guides/getting-started-ucls-vpn">active VPN connection</a> that links your personal computer into UCL’s network. Students in mainland China may want to use <a href="https://www.ucl.ac.uk/isd/services/get-connected/china-connect">UCL China Connect</a>. Students that use a Mac computer that is running on the latest version of MacOS (<a href="https://www.apple.com/uk/macos/big-sur/">MacOS Big Sur</a>), are advised to use <a href="https://www.ucl.ac.uk/isd/services/computers/remote-access/desktopucl-anywhere">Desktop@UCL</a> as the Cisco AnyConnect VPN application may not work. If you are completely unable to access the server (e.g. your browser displays a <em>This site can’t be reached</em> message), it means that your VPN connection is not working correctly. Please ensure that your VPN is working correctly or use <a href="https://www.ucl.ac.uk/isd/services/computers/remote-access/desktopucl-anywhere">Desktop@UCL Anywhere</a> instead.</p>
</div>
</div>
<div id="an-introduction-to-r-studio-and-its-interface" class="section level4 unnumbered">
<h4>An Introduction to R-Studio and its interface</h4>
<p>Let’s go ahead and open R-Studio (Desktop or Server) and we’ll first take a quick tour of the various components of the R-Studio environment interface and how and when to use them:</p>
<center>
<strong>Introducing the R-Studio Interface</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/79bb3915-0085-4f6d-9829-5d97ff44d85a?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://web.microsoftstream.com/video/79bb3915-0085-4f6d-9829-5d97ff44d85a">Video on Stream</a>
</center>
<p><br></p>
<p>As you’ve heard, R-Studio has various windows that you use for different purposes - and you can customise its layout dependent on your preference.</p>
<p>When you first open R-Studio, it should look a little something like this:</p>
<p><img src="images/w4/04_rstudio_interface.png" width="650pt" style="display: block; margin: auto;" /></p>
<p>The main windows (panel/pane) to keep focused on for now are:</p>
<ul>
<li><p><strong>Console</strong>: where we write “one-off” code, such as installing libraries/packages, as well as running quick views or plots of our data.</p></li>
<li><p><strong>Files</strong>: where our files are stored on our computer system - can help with checking file paths as well as file names, and general file management.</p></li>
<li><p><strong>Environment</strong>: where our variables are recorded - we can find out <strong>a lot</strong> about our variables by looking at the Environment window, including data structure, data type(s) and the fields and ‘attributes’ of our variables.</p></li>
<li><p><strong>Plots</strong>: the outputs of our graphs, charts and maps are shown here.</p></li>
<li><p><strong>Help</strong>: where you an search for help, e.g. by typing in a function to find out its parameters.</p></li>
</ul>
<p>You may also have your <strong>Script Window</strong> open, which is where we build up and write code, to a) keep a record of our work, b) enable us to repeat and re-run code again, often with different parameters. We will not use this window until we get to the final practical instructions.</p>
<p>We’ll see how we use these windows as we progress through this tutorial and understand in more detail what we mean by words such as ‘attributes’ (do not get confused here with the <strong>Attribute Table</strong> for Q-GIS) and data structures.</p>
</div>
<div id="programming-for-data-analysis-1" class="section level4 unnumbered">
<h4>Programming for Data Analysis</h4>
<p>Before we get started with using R-Studio, we first need to take a few steps back and address the bigger learning curve in the room, that is: <strong>How do I program?</strong>.</p>
<p>As stated earlier, R/R-Studio is just a tool - but to use it, you need to understand how to write code in R effectively and, of course, accurately to get your analysis to work.</p>
<p>This means we need to learn about and understand:</p>
<ul>
<li><strong>Basic Syntax</strong></li>
<li><strong>Data Structures and Types</strong></li>
<li><strong>Functions and Libraries/Packages</strong></li>
<li><strong>Object-Oriented Programming</strong></li>
</ul>
<p>Here, we provide a short introduction to the basic principles of programming, with a focus on Object Oriented Programming.</p>
<p>This is a video you might want to re-watch after completing today’s practical.</p>
<center>
<strong>Principles of Programming for Data Analysis</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/3286b44f-1bd7-488a-baed-d1376e69c9f5?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://liveuclac-my.sharepoint.com/:b:/g/personal/ucfailk_ucl_ac_uk/EVNCaN-2CrVBn5KAOKM1bGUBcXJKWQqmR964v-CB3nEmTg?e=jIs48s">Slides</a> | <a href="https://web.microsoftstream.com/video/3286b44f-1bd7-488a-baed-d1376e69c9f5">Video on Stream</a>
</center>
<p><br></p>
<p>In the above lecture, you heard about the different including:</p>
<ul>
<li><p>Syntax using <strong>variables</strong> and <strong>functions</strong></p></li>
<li><p>Importance of <strong>data types</strong> and <strong>data structures</strong></p></li>
<li><p>The role of <strong>packages/libraries</strong> in expanding R’s functionality</p></li>
<li><p>And a brief introduction to Object-Oriented Programin (OOP)</p></li>
</ul>
<p>We can put some of these principles into action by testing some of R-Studio’s capability with some short pieces of coding now.</p>
</div>
<div id="using-the-console-in-r-studio" class="section level4 unnumbered">
<h4>Using the Console in R-Studio</h4>
<p>We’ll first start off with using <strong>R-Studio’s console</strong> to test out some of R’s in-built functionality by creating a few variables as well as a dummy dataset that we’ll be able to analyse - and to get familiar with writing code.</p>
<p><em>Note, you might need to click on the console window to get it to expand - you can then drag it to take up a larger space in your R-Studio window.</em></p>
<p>The video below provides an overview of the short tutorial with additional explanations, so if you’re already a bit stuck, you can watch this as you start to complete the following instructions.</p>
<center>
<strong>Using the Console in R-Studio for programming</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/2508bfa9-865d-4fea-86f7-4398e4c64f78?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<center>
<a href="https://web.microsoftstream.com/video/2508bfa9-865d-4fea-86f7-4398e4c64f78">Video on Stream</a>
</center>
<p><br></p>
<p>In your R-Studio console, you should see a prompt sign - <strong>&gt;</strong> to the left - this means we’re ready to start writing code (a bit like earlier in the shell).</p>
<div class="codetime">
<p><strong>Error Warnings in the Console</strong><br></p>
<p>Anything that appears as red in the command line means it is an error (or a warning) so you will likely need to correct your code.</p>
<p>If you see a <code>&gt;</code> on the left it means you can type in your next line, a <code>+</code> means that you haven’t finished the previous line of code.</p>
<p>As will become clear, <code>+</code> signs often appear if you don’t close brackets or you did not properly finish your command in a way that R expected.</p>
</div>
<p>In your console, let’s go ahead and conduct some quick maths - at their most basic, all programming langauges can work like calculators!</p>
<p><strong>Command Input</strong></p>
<ol style="list-style-type: decimal">
<li>Type in <code>10 * 12</code> into the console.</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="co"># Conduct some maths</span></a>
<a class="sourceLine" id="cb1-2" title="2"><span class="dv">10</span> <span class="op">*</span><span class="st"> </span><span class="dv">12</span></a></code></pre></div>
<pre><code>## [1] 120</code></pre>
<p>Once you press return, you should see the answer of 120 returned below.</p>
<p>Great, you’ve now learnt how to enter code into the R-Studio console! Pretty similar to your computer’s CLI right?!</p>
<p><strong>Storing Variables</strong></p>
<p>But rather than use ‘raw’ or ‘standalone’ numbers and values, we primarily want to use variables that stores these values (or groups of them) under a memorable name for easy reference later.</p>
<p>In R terminology this is called <strong>creating an object</strong> and this object becomes stored as a <strong>variable</strong>.</p>
<p>We do this by using the <code>&lt;-</code> symbol is used to assign the value to the variable name you have given.</p>
<p>Let’s go ahead and try this.</p>
<p>Let’s create two variables for experimenting with:</p>
<p>2.Type in <code>ten &lt;- 10</code> into the console and execute.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="co"># Store our ten variable</span></a>
<a class="sourceLine" id="cb3-2" title="2">ten &lt;-<span class="st"> </span><span class="dv">10</span></a></code></pre></div>
<p>You have just created your first variable.</p>
<p>You will see nothing is returned in the console - but if you check your Environment window, it has now appeared as a new variable that contains the associated value.</p>
<ol start="3" style="list-style-type: decimal">
<li>Type in <code>twelve &lt;- 12</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="co"># Store our ten variable</span></a>
<a class="sourceLine" id="cb4-2" title="2">twelve &lt;-<span class="st"> </span><span class="dv">12</span></a></code></pre></div>
<p>Once again, you’ll see nothing returned to the console but do check your Environment window for your variable.</p>
<p>We’ve now stored two <strong>numbers</strong> into our environment - and given them pretty good variable names for easy reference.</p>
<p>R stores these objects as variables in your computer’s RAM so they can be processed quickly.</p>
<p>Without saving your environment (we will come onto this below), these variables would be lost if you close R (or it crashes).</p>
<p>Now we have our variables, let’s go ahead and do the same simple multiplication maths:</p>
<ol start="4" style="list-style-type: decimal">
<li>Type in <code>ten * twelve</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="co"># Conduct some maths again using our variables</span></a>
<a class="sourceLine" id="cb5-2" title="2">ten <span class="op">*</span><span class="st"> </span>twelve</a></code></pre></div>
<pre><code>## [1] 120</code></pre>
<p>You should see the output in the console of <strong>120</strong> (of course..!).</p>
<p>Whilst this maths may look trivial, it is, in fact, extremely powerful as it shows how these <strong>variables</strong> can be treated in the same way as the values they contain.</p>
<ol start="5" style="list-style-type: decimal">
<li>Next, type in <code>ten * twelve * 8</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="co"># Conduct some more maths with variables and raw values</span></a>
<a class="sourceLine" id="cb7-2" title="2">ten <span class="op">*</span><span class="st"> </span>twelve <span class="op">*</span><span class="st"> </span><span class="dv">8</span></a></code></pre></div>
<pre><code>## [1] 960</code></pre>
<p>You should get an answer of 960. As you can see, we can mix <strong>variables</strong> with <strong>raw values</strong> without any problems.</p>
<p>We can also <strong>store the output of variable calculations</strong> as a <strong>new variable</strong>.</p>
<ol start="6" style="list-style-type: decimal">
<li>Type <code>output &lt;- ten * twelve * 8</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="co"># Conduct some maths and store it as output</span></a>
<a class="sourceLine" id="cb9-2" title="2">output &lt;-<span class="st"> </span>ten <span class="op">*</span><span class="st"> </span>twelve <span class="op">*</span><span class="st"> </span><span class="dv">8</span></a></code></pre></div>
<p>As we’re storing the output of our maths to a new variable, the answer won’t be returned to the screen.</p>
<p><strong>Accessing and returning variables</strong></p>
<p>We can ask our computer to return this <code>output</code> by simply typing it into the console.</p>
<ol start="7" style="list-style-type: decimal">
<li>Ask the computer to return the variable <code>output</code>. You should see we get the same value as the earlier equation.</li>
</ol>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="co"># Return the variable, output</span></a>
<a class="sourceLine" id="cb10-2" title="2">output</a></code></pre></div>
<pre><code>## [1] 960</code></pre>
<p><strong>Variables of different data types</strong></p>
<p>We can also store variables of different data types, not just numbers but text as well.</p>
<ol start="8" style="list-style-type: decimal">
<li>Type in <code>str_variable &lt;- "This is our first string variable"</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="co"># Store a variable</span></a>
<a class="sourceLine" id="cb12-2" title="2">str_variable &lt;-<span class="st"> &quot;This is our 1st string variable&quot;</span></a></code></pre></div>
<p>We have just stored our sentence made from a combination of characters, including letters and numbers.</p>
<p>A variable that stores “words” (that may be sentences, or codes, or file names), is known as a string. A string is always denoted by the use of the <strong>" "</strong>.</p>
<p>Let’s access our variable to see what is now stored by our computer.</p>
<ol start="9" style="list-style-type: decimal">
<li>Type in <code>str_variable</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="co"># Return our str_variable</span></a>
<a class="sourceLine" id="cb13-2" title="2">str_variable</a></code></pre></div>
<pre><code>## [1] &quot;This is our 1st string variable&quot;</code></pre>
<p>You should see our entire sentence returned - and enclosed in <strong>""</strong>.</p>
<p>Again, by simply entering our variable into the console, we have asked R to return our variable to us.</p>
<p><strong>Calling functions on our variables</strong></p>
<p>We can also <strong>call</strong> a function on our variable.</p>
<p>This use of <strong>call</strong> is a very specific programming term and generally what you use to say <em>"use</em>" a function.</p>
<p>What it simply means is that we will use a specific <strong>function</strong> to <strong>do something</strong> to our variable.</p>
<p>For example, we can also ask R to <strong>print</strong> our variable, which will give us the same output as accessing it directly via the console:</p>
<ol start="10" style="list-style-type: decimal">
<li>Type in <code>print(str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="co"># Print str_variable to the screen</span></a>
<a class="sourceLine" id="cb15-2" title="2"><span class="kw">print</span>(str_variable)</a></code></pre></div>
<pre><code>## [1] &quot;This is our 1st string variable&quot;</code></pre>
<p>We have just used our first function: <code>print()</code>. This function actively finds the variable and then <strong>returns</strong> this to our screen.</p>
<p>You can type <code>?print</code> into the console to find out more about the <code>print()</code> function.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="co"># Gain access to the documentation for our print function</span></a>
<a class="sourceLine" id="cb17-2" title="2">?print</a></code></pre></div>
<p>This can be used with any function to get access to their <strong>documentation</strong> which is essential to know how to use the function correctly <strong>and</strong> understand its output.</p>
<p>In many cases, a function will take more than one <strong>argument</strong> or <strong>parameter</strong>, so it is important to know what you need to provide the function with in order for it to work.</p>
<p>For now, we are using functions that only need one argument.</p>
<p><strong>Returning functions</strong></p>
<p>When a function provides an output, such as this, it is known as <strong>returning</strong>.</p>
<p>Not all functions will <em>return</em> an output to your screen - they’ll simply just <em>do</em> what you access them to do, so often we’ll use a <code>print()</code> <strong>statement</strong> or another type of <strong>returning</strong> function to check whether the function was successful or not - more on this later in the workshop.</p>
<p><strong>Examining our variables using functions</strong></p>
<p>Within the <strong>base</strong> R language, there are various functions that have been written to help us examine and find out information about our variables.</p>
<p>For example, we can use the <code>typeof()</code> function to check what data type our variable is:</p>
<ol start="11" style="list-style-type: decimal">
<li>Type in <code>typeof(str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="co"># Call the typeof() function on str_variable to return the data type of our variable.</span></a>
<a class="sourceLine" id="cb18-2" title="2"><span class="kw">typeof</span>(str_variable)</a></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>You should see the answer: <code>"character"</code>. As evident, our <code>str_variable</code> is a character data type.</p>
<p>We can try testing this out on one of our earlier variables.</p>
<ol start="12" style="list-style-type: decimal">
<li>Type in <code>typeof(ten)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="co"># Call the typeof() function on ten variable to return the data type of our variable.</span></a>
<a class="sourceLine" id="cb20-2" title="2"><span class="kw">typeof</span>(ten)</a></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<p>You should see the answer: <code>"double"</code>. As evident, our <code>ten</code> is a double data type.</p>
<p>For high-level objects that involve (more complicated) data structures, such as when we load a csv into R as a <strong>data frame</strong>, we are also able to check what <strong>class</strong> our object is, as follows:</p>
<ol start="13" style="list-style-type: decimal">
<li>Type in <code>class(str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="co"># Call the class() function on str_variable to return the object of our variable.</span></a>
<a class="sourceLine" id="cb22-2" title="2"><span class="kw">class</span>(str_variable)</a></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>In this case, you’ll get the same answer - <strong>“character”</strong> - because, in R, both its class and type are the same: a character.</p>
<p>In other programming languages, you might have had <code>"string"</code> returned instead, but this effectively means the same thing.</p>
<p>Let’s try testing our <code>ten</code> variable:</p>
<ol start="14" style="list-style-type: decimal">
<li>Type in <code>class(ten)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="co"># Call the class() function on ten to return the object of our variable.</span></a>
<a class="sourceLine" id="cb24-2" title="2"><span class="kw">class</span>(ten)</a></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>In this case, you’ll get a different answer - <code>"numeric"</code> - because the class of this variable is numeric.</p>
<p>This is because the class of numeric objects can contain either doubles (decimals) or integers (whole numbers).</p>
<p>We can test this by asking whether our <code>ten</code> variable is an integer or not.</p>
<ol start="15" style="list-style-type: decimal">
<li>Type in <code>is.integer(ten)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="co"># Test our ten variable by asking if it is an integer</span></a>
<a class="sourceLine" id="cb26-2" title="2"><span class="kw">is.integer</span>(ten)</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>You should see we get the answer <code>FALSE</code> - as we know from our earlier <code>typeof()</code> function, our variable ten is stored as a double and therefore cannot be an integer.</p>
<p>Whilst knowing this might not seem important now, but when it comes to our data analysis, the difference of a decimal number vs. a whole number can quite easily add bugs into our code!</p>
<p>We can incorporate these tests into our code when we need to evaluate an output of a process and do some quality assurance testing of our data analysis.</p>
<p>We can also ask how <strong>long</strong> our variable is - in this case, we’ll find out how many different <strong>sets</strong> of characters (strings) are stored in our variable, <code>str_variable</code>.</p>
<ol start="15" style="list-style-type: decimal">
<li>Type in <code>length(str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="co"># Call the length() function on str_variable to return the length of our variable.</span></a>
<a class="sourceLine" id="cb28-2" title="2"><span class="kw">length</span>(str_variable)</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>You should get the answer <code>1</code> - as we only have one set of characters.</p>
<p>We can also ask how long each set of characters is within our variable, i.e. ask how long the string contained by our variable is.</p>
<ol start="8" style="list-style-type: decimal">
<li>Type in <code>nchar(str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="co"># Call the nchar() function on str_variable to return the length of each of our elements within our variable.</span></a>
<a class="sourceLine" id="cb30-2" title="2"><span class="kw">nchar</span>(str_variable)</a></code></pre></div>
<pre><code>## [1] 31</code></pre>
<p>You should get an answer of <code>31</code>.</p>
<p><strong>Creating a two-element object</strong></p>
<p>Let’s go ahead and test these two functions a little further by creating a new variable to store two string sets within our object, i.e. our variable will hold two elements.</p>
<ol start="9" style="list-style-type: decimal">
<li>Type in <code>two_str_variable &lt;- c("This is our second variable", "It has two parts to it")</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="co"># Store a new variable with two items using the c() function</span></a>
<a class="sourceLine" id="cb32-2" title="2">two_str_variable &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;This is our second string variable&quot;</span>, <span class="st">&quot;It has two parts to it&quot;</span>)</a></code></pre></div>
<p>In this piece of code, we’ve created a new variable using the <strong>c</strong> function in R, that stands for <strong>"combine values into a vector or list</strong>.</p>
<p>We’ve provided that function with two sets of strings, using a <strong>comma</strong> to separate our two strings - all contained within the function’s <strong>()</strong>.</p>
<p>You should now see a new variable in your Environment window which tells us it’s a) chr: characters, b) contains 2 items, and c) lists those items.</p>
<p>Let’s now try both our <strong>length()</strong> and <strong>nchar()</strong> on our new variable and see what the results are.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1"><span class="co"># Call the length() function and nchar() function on our new variable</span></a>
<a class="sourceLine" id="cb33-2" title="2"><span class="kw">length</span>(two_str_variable)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">nchar</span>(two_str_variable)</a></code></pre></div>
<pre><code>## [1] 34 22</code></pre>
<p>Did you see a difference?</p>
<p>You should have seen that the <code>length()</code> function now returned a <strong>2</strong> and the <code>nchar()</code> function returned two values of <strong>34 and 22</strong>.</p>
<p>There is one final function that we often want to use with our variables when we are first exploring them, which is <code>attributes()</code> - as our variables are very simple, they currently do not have any attributes (you are welcome to type in the code and try) but it is a really useful function, which we’ll come across later on.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1"><span class="co"># Call the attributes() function on our new variable</span></a>
<a class="sourceLine" id="cb37-2" title="2"><span class="kw">attributes</span>(two_str_variable)</a></code></pre></div>
<pre><code>## NULL</code></pre>
<p>We’ve had fun experimenting with simple variables in our console - and learnt about <strong>many new functions</strong> we can use with our code.</p>
<p>In fact, we’ve learnt <strong>7</strong> functions - <strong>can you name/remember them all without scrolling up?</strong></p>
<p>If you can’t, I <strong>highly recommend</strong> taking notes on each of the functions - even if it is just a <strong>short list</strong> of the functions and what they do.</p>
<p>We’re now going to move on to creating and analysing our dummy dataset - so fingers crossed you’ll remember these as we move forward.</p>
<div class="codetime">
<p><strong>Using comments in our code</strong><br></p>
<p>In addition to make notes about the functions you are coming across in the workshop, you should notice that with each line of code I have written, I have provided an additional <strong>comment</strong> to explain what the code does.</p>
<p>Comments are denoted using the hash symbol <strong>#</strong>. This comments out that particular line so that R ignores it when the code is run.</p>
<p>These comments will help you in future when you return to scripts a week or so after writing the code - as well as help others understand what is going on when sharing your code.</p>
<p>It is good practice to get into writing comments <strong>as you code</strong> and not leave it to do retrospectively - because I can tell you from experience - you most certainly will not.</p>
<p>Whilst we are using the console, using comments is not necessary - but as we start to build up a script in our full practical, you’ll find them essential to help understand your workflow in the future!</p>
</div>
</div>
<div id="analysing-dummy-data-in-r-studio-using-the-console" class="section level4 unnumbered">
<h4>Analysing dummy data in R-Studio using the Console</h4>
<p>The objects we created and played with above are very simple: we have stored either simple strings or numeric values - but the real power of R comes when we can begin to execute functions on more complex objects.</p>
<p>As we heard in our lecture, R accepts <strong>four</strong> main types of data structures: <strong>vectors</strong>, <strong>matrices</strong>, <strong>data frames</strong>, and <strong>lists</strong>.</p>
<p>So far, we have dabbled with a single item or a dual item <strong>vector</strong> - for the latter, we used the <code>c()</code> function to allow us to combine our two strings together within a single vector.</p>
<p>We can use this same function to create and build more complex objects - which we can then use with some common <strong>statistical functions</strong>.</p>
<p>We’re going to try this out by using a simple set of dummy data: we’re going to use the total number of pages and publication dates of the various editions of <strong>Geographic Information Systems and Science (GISS)</strong> for our brief dummy analysis:</p>
<table>
<thead>
<tr class="header">
<th align="left">Book Edition</th>
<th align="left">Year</th>
<th align="left">Total Number of Pages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1st</td>
<td align="left">2001</td>
<td align="left">454</td>
</tr>
<tr class="even">
<td align="left">2nd</td>
<td align="left">2005</td>
<td align="left">517</td>
</tr>
<tr class="odd">
<td align="left">3rd</td>
<td align="left">2011</td>
<td align="left">560</td>
</tr>
<tr class="even">
<td align="left">4th</td>
<td align="left">2015</td>
<td align="left">477</td>
</tr>
</tbody>
</table>
<p>As we can see, we will ultimately want to store the data in a table as above (and we could easily copy this to a csv to load into R if we wanted).</p>
<p>But <strong>we want to learn a little more about data structures in R</strong>, therefore, we’re going to go ahead and build this table “manually”.</p>
<p>Let’s get going.</p>
<p><strong>Clearing our Environemnt workspace</strong></p>
<p>First, let’s clear up our workspace and remove our current variables:</p>
<ol start="10" style="list-style-type: decimal">
<li>Type <code>rm(ten, twelve, output, str_variable, two_str_variable)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="co"># Clear our workspace</span></a>
<a class="sourceLine" id="cb39-2" title="2"><span class="kw">rm</span>(ten, twelve, output, str_variable, two_str_variable)</a></code></pre></div>
<p><strong>Note, of course you can either copy and paste this code - or try out using the tab function to autocomplete your variable names in the console as you start typing them in, just as we did when using the Command Line.</strong></p>
<p>You should now see we no longer have any variables in our window - we just used the <code>rm()</code> function to <strong>remove</strong> these variables from our environment.</p>
<p>Keeping a clear workspace is another recommendation of good practice moving forward.</p>
<p>Of course, we do not want to get rid of any variables we might need to use later - but removing any variables we no longer need (such as test variables) will help you understand and manage your code and your working environment.</p>
<p><strong>Creating an atomic vector of multiple elements</strong></p>
<p>The first complex data object we will create is a vector.</p>
<p>A vector is the most common and basic data structure in R and is pretty much the workhorse of R.</p>
<p>Vectors are a collection of elements that are mostly of either character, logical integer or numeric data types.</p>
<p>Technically, vectors can be one of two types:</p>
<ul>
<li><strong>Atomic vectors</strong> (all elements are of the same data type)</li>
<li><strong>Lists</strong> (elements can be of different data types)</li>
</ul>
<p>Although in practice the term “vector” most commonly refers to the atomic types and not to lists.</p>
<p>The variables we created above are actually vectors - however they are made of only one or two elements. We want to make complex vectors with more elements to them.</p>
<p>Let’s create our first official “complex” vector, detailing the different total page numbers for GISS:</p>
<ol start="11" style="list-style-type: decimal">
<li>Type <code>giss_page_no &lt;- c(454, 517, 560, 477)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="co"># store our total number of pages, in chronological order, as a variable</span></a>
<a class="sourceLine" id="cb40-2" title="2">giss_page_no &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">454</span>, <span class="dv">517</span>, <span class="dv">560</span>, <span class="dv">477</span>)</a></code></pre></div>
<p>Let’s check the results.</p>
<ol start="12" style="list-style-type: decimal">
<li>Type <code>print(giss_page_no)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="co"># print our giss... variable</span></a>
<a class="sourceLine" id="cb41-2" title="2"><span class="kw">print</span>(giss_page_no)</a></code></pre></div>
<pre><code>## [1] 454 517 560 477</code></pre>
<p>We can see we have our total number of pages collected together in a single vector. We could if we want, execute some statistical functions on our vector object:</p>
<ol start="13" style="list-style-type: decimal">
<li>Type our various statistical functions (detailed below) into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="co"># calculate the arithmetic mean on our variable</span></a>
<a class="sourceLine" id="cb43-2" title="2"><span class="kw">mean</span>(giss_page_no)</a></code></pre></div>
<pre><code>## [1] 502</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="co"># calculate the median on our variable</span></a>
<a class="sourceLine" id="cb45-2" title="2"><span class="kw">median</span>(giss_page_no)</a></code></pre></div>
<pre><code>## [1] 497</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="co"># calculate the range numbers of our variable</span></a>
<a class="sourceLine" id="cb47-2" title="2"><span class="kw">range</span>(giss_page_no)</a></code></pre></div>
<pre><code>## [1] 454 560</code></pre>
<p>We have now completed our first set of <strong>descriptive statistics</strong> in R!</p>
<p>We now know that the average number of pages the GISS book has contain is 497 pages - this is of course truly thrilling stuff, but hopefully an easy example to get onboard with.</p>
<p>But let’s see how we can build on our vector object by adding in a second vector object that details the relevant years of our book.</p>
<p><em>Note, I entered the total number of pages in a specific order to correspond to these publishing dates (i.e. chronological), as outlined by the table above.</em></p>
<p>As a result, I’ll enter the publication year in the same order.</p>
<ol start="14" style="list-style-type: decimal">
<li>Type <code>giss_year &lt;- c(2001, 2005, 2011, 2015)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="co"># store our publication years, in chronological order, as a variable</span></a>
<a class="sourceLine" id="cb49-2" title="2">giss_year &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2001</span>, <span class="dv">2005</span>, <span class="dv">2011</span>, <span class="dv">2015</span>)</a></code></pre></div>
<p>Let’s check the results.</p>
<ol start="14" style="list-style-type: decimal">
<li>Type <code>print(giss_year)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1"><span class="co">#print our giss_year variable</span></a>
<a class="sourceLine" id="cb50-2" title="2"><span class="kw">print</span>(giss_year)</a></code></pre></div>
<pre><code>## [1] 2001 2005 2011 2015</code></pre>
<p>Again, truly exciting stuff.</p>
<p>Of course, on their own, the two vectors do not mean much - but we can use the same <code>c()</code> function to combine the two together to create a matrix.</p>
<p><strong>Creating a matrix from two vectors</strong></p>
<p>In R, a matrix is simply an extension of the numeric or character vectors.</p>
<p>They are not a separate type of object per se but simply a vector that has two dimensions.</p>
<p>That is they contain both <strong>rows</strong> and <strong>columns</strong>.</p>
<p>As with atomic vectors, the elements of a matrix must be of the <strong>same data type</strong>.</p>
<p>As both our page numbers and our years are numeric (<em>we can check this using which function?</em>), we can add them together to create a matrix using the <code>matrix()</code> function:</p>
<ol start="15" style="list-style-type: decimal">
<li>Type <code>giss_year_nos &lt;- matrix(c(giss_year, giss_page_no), ncol=2)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1"><span class="co"># create a new matrix from our two vectors with two columns</span></a>
<a class="sourceLine" id="cb52-2" title="2">giss_year_nos &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(giss_year, giss_page_no), <span class="dt">ncol=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb52-3" title="3"></a>
<a class="sourceLine" id="cb52-4" title="4"><span class="co"># note the inclusion of a new argument to our matrix: ncol=2</span></a>
<a class="sourceLine" id="cb52-5" title="5"><span class="co">#this stands for &quot;number of columns&quot; and we want two.</span></a></code></pre></div>
<p>Again, let’s check the results.</p>
<ol start="16" style="list-style-type: decimal">
<li>Type <code>print(giss_year_nos)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">print</span>(giss_year_nos)</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,] 2001  454
## [2,] 2005  517
## [3,] 2011  560
## [4,] 2015  477</code></pre>
<p>The thing about matrices - as you might see above - is that, for us, they don’t have a huge amount of use.</p>
<p>If we were to look at this matrix in isolation from what we know it represents, we wouldn’t really know what to do with it.</p>
<p>As a result, we tend to primarily use <strong>Data Frames</strong> in R as they offer the opportunity to add <strong>field names</strong> to our columns to help with their intepretation.</p>
<div class="codetime">
<p><strong>Arguments/Parameters in Functions</strong><br></p>
<p>The function we just used above, ‘matrix()’, was the first function that we used that took more than one argument.</p>
<p>In this case, the arguments the matrix needed to run were:</p>
<ol style="list-style-type: decimal">
<li>What data or dataset should be stored in the matrix.</li>
<li>How many columns (<code>ncol=</code>) do we need to store our data in.</li>
</ol>
<p>The function can actually accept several more arguments - but these were not of use for us in this scenario, so we did not include them.</p>
<p>For almost any R package, <strong>the documentation will contain a list of the arguments that the function will takes, as well as in which format the functions expects these arguments</strong> and a set of usage examples.</p>
<p>Understanding how to find out what object and data type a variable is essential therefore to knowing whether it can be used within a function - and whether we will need to transform our variable into a different data structure to be used for that specific function.</p>
<p>For any function, there will be <strong>mandatory</strong> arguments (i.e. it will not run without these) or <strong>optional</strong> arguments (i.e. it will run without these, as the default to this argument has been set usually to FALSE, 0 or NULL).</p>
</div>
<p><strong>Creating a Data Frame from our matrix</strong></p>
<p>A data frame is an extremely important data type in R.</p>
<p>It is pretty much the <strong>de-facto data structure</strong> for most tabular data and what we use for statistics.</p>
<p>It also is the underlying structure to the table data (what we would call the <strong>attribute table</strong> in Q-GIS) that we associate with spatial data - more on this next week.</p>
<p>A data frame is a special type of list where every element of the list will have the same length (i.e. data frame is a “rectangular” list),</p>
<p>Essentially, a data frame is constructed from columns (which represent a list) and rows (which represents a corresponding element on each list). Each column will have the same amount of entries - even if, for that row, for example, the entry is simply NULL.</p>
<p>Data frames can have additional attributes such as <code>rownames()</code>, which can be useful for annotating data, like <code>subject_id</code> or <code>sample_id</code> or even <code>UID</code>. In statistics, they are often not used - but in spatial analysis, these IDs can be very useful.</p>
<p>Some additional information on data frames:</p>
<ul>
<li><p>They are usually created by <code>read.csv()</code> and <code>read.table()</code>, i.e. when importing the data into R.</p></li>
<li><p>Assuming all columns in a data frame are of same type, a data frame can be converted to a matrix with <code>data.matrix()</code> (preferred) or<code>as.matrix()</code>.</p></li>
<li><p>You can also create a new data frame with <code>data.frame()</code> function, e.g. a matrix can be converted to a data frame, as we’ll see below.</p></li>
<li><p>You can find out the number of rows and columns with <code>nrow()</code> and <code>ncol()</code>, respectively.</p></li>
<li><p>Rownames are often automatically generated and look like 1, 2, …, n. Consistency in numbering of rownames may not be honoured when rows are reshuffled or subset.</p></li>
</ul>
<p>Let’s go ahead and create a new data frame from our matrix:</p>
<ol start="16" style="list-style-type: decimal">
<li>Type <code>giss_df &lt;- data.frame(giss_year_nos)</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="co"># Create a new dataframe from our matrix</span></a>
<a class="sourceLine" id="cb55-2" title="2">giss_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(giss_year_nos)</a></code></pre></div>
<p>We now have a data frame, we can finally use the <code>View()</code> function in R.</p>
<ol start="17" style="list-style-type: decimal">
<li>Still in your <strong>console</strong>, type: <code>View(giss_df)</code></li>
</ol>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="co"># View our data frame</span></a>
<a class="sourceLine" id="cb56-2" title="2"><span class="kw">View</span>(giss_df)</a></code></pre></div>
<p>You should now see a table pop-up as a new tab on your script window.</p>
<p>It’s now starting to look like our original table - but we’re not exactly going to be happy with <strong>X1</strong> and <strong>X2</strong> as our field names - they’re not very informative.</p>
<p><strong>Renaming our column field names</strong></p>
<p>Instead, what we can do is <strong>rename</strong> our data frame column field names by using the <code>names()</code> function.</p>
<p>Before we do this, have a read of what the <code>names()</code> function does.</p>
<ol start="18" style="list-style-type: decimal">
<li>Still in your <strong>console</strong>, type: <code>?names</code></li>
</ol>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="co"># Get the help documentation for the names function</span></a>
<a class="sourceLine" id="cb57-2" title="2">?names</a></code></pre></div>
<p>As you can see, the function will get or set the names of an object, with renaming occuring by using the following syntax:</p>
<p><code>names(x) &lt;- value</code></p>
<p>The value itself needs to be <em>a character vector of up to the same length as x, or NULL.</em></p>
<p>This is one of the cool aspects of OOP, in that we can access specific parts of our object and change it without changing the object as a whole or having to create a new object/variable to enact our changes.</p>
<p>We have two columns in our data frame, so we need to parse our <code>names()</code> function with a character vector with <strong>two elements</strong>.</p>
<ol start="19" style="list-style-type: decimal">
<li>In the console, we shall enter two lines of code, one after another. First our character vector with our new names, <code>new_names &lt;- c("year", "page_nos")</code>, and then the <code>names()</code> function containing this vector for renaming, <code>names(giss_df) &lt;- new_names</code>:</li>
</ol>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="co"># Create a vector with our new column names</span></a>
<a class="sourceLine" id="cb58-2" title="2">new_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;page_nos&quot;</span>)</a>
<a class="sourceLine" id="cb58-3" title="3"></a>
<a class="sourceLine" id="cb58-4" title="4"><span class="co">#Rename our columns with our next names</span></a>
<a class="sourceLine" id="cb58-5" title="5"><span class="kw">names</span>(giss_df) &lt;-<span class="st"> </span>new_names</a></code></pre></div>
<p>You can go and check your data frame again and see the new names using either <code>View()</code> function or by clicking on the tab at the top.</p>
<p><strong>Adding a column to our data frame</strong></p>
<p>We are still missing one final column from our data frame - that is our <strong>edition</strong> of the textbook. As this is a <strong>character</strong> data type, we would not have been able to add this directly to our matrix - and instead have waited until we have our data frame to do so.</p>
<p>This is because data frames can take different data types, unlike matrices - so let’s go ahead and add the <strong>edition</strong> as a new column.</p>
<p>To do so, we follow a similar process of creating a vector with our editions listed in chronological order, but then add this to our data frame by storing this vector as a new column in our data frame.</p>
<p>We use the <strong>$</strong> sign with our code that gives us “access” to the data frame’s column - we then specify the column <code>edition</code>, which whilst it does not exist at the moment, will be created from our code that assigns our edition variable to this column.</p>
<p>This <strong>$</strong> is another feature of OOP.</p>
<p>Let’s take a look.</p>
<ol start="20" style="list-style-type: decimal">
<li>Create a <code>edition</code> vector variable containing our textbook edition numbers - type and execute <code>edition &lt;- c("1st", "2nd", "3rd", "4th")</code>. We then store this as a new column in our data frame under the column name <strong>edition</strong> by typing and executing <code>giss_df$edition &lt;- edition</code>:</li>
</ol>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="co"># Create a vector with our editions</span></a>
<a class="sourceLine" id="cb59-2" title="2">edition &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;1st&quot;</span>, <span class="st">&quot;2nd&quot;</span>, <span class="st">&quot;3rd&quot;</span>, <span class="st">&quot;4th&quot;</span>)</a>
<a class="sourceLine" id="cb59-3" title="3"></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="co"># Add this vector as a new column to our data frame</span></a>
<a class="sourceLine" id="cb59-5" title="5">giss_df<span class="op">$</span>edition &lt;-<span class="st"> </span>edition</a></code></pre></div>
<p>Again, you can go and check your data frame and see the new column using either <code>View()</code> function or by clicking on the tab at the top.</p>
<p>You should now have a data frame that looks like:</p>
<p><img src="images/w4/dataframe.png" width="250pt" style="display: block; margin: auto;" /></p>
<p>Now we have our data frame, let’s find out a little about it.</p>
<p>We can first return the dimensions (the size) of our data frame by using the <code>dim()</code> function (<em>dim simply stands for dimensions in this case.</em>).</p>
<ol start="21" style="list-style-type: decimal">
<li>In your <strong>console</strong>, type <code>dim(giss_df)</code> and execute:</li>
</ol>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="co"># Check our data frame dimensions</span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="kw">dim</span>(giss_df)</a></code></pre></div>
<pre><code>## [1] 4 3</code></pre>
<p>We can see we have <strong>four rows</strong> and <strong>three columns</strong>.</p>
<p>And we can finally use our <code>attributes()</code> function to get the attributes of our data frame.</p>
<ol start="22" style="list-style-type: decimal">
<li>In your <strong>console</strong>, type <code>attributes(giss_df)</code> and execute:</li>
</ol>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="co"># Check our data frame attributes</span></a>
<a class="sourceLine" id="cb62-2" title="2"><span class="kw">attributes</span>(giss_df)</a></code></pre></div>
<pre><code>## $names
## [1] &quot;year&quot;     &quot;page_nos&quot; &quot;edition&quot; 
## 
## $row.names
## [1] 1 2 3 4
## 
## $class
## [1] &quot;data.frame&quot;</code></pre>
<p>You should see that we now get a list of the column and row names, plus the class of the data frame.</p>
<p>There is <strong>a lot more</strong> we could now do with our data frame but we simply do not have time - and we’d much rather implement some of these functions or data management techniques with a much more exciting dataset than the details of the <strong>GISS</strong> textbook.</p>
<p>Hopefully though, this has served as a good introduction to the different data structures you’ll be coming across over the next 6 weeks as we use R - and provided you with some simple code you can return to time and time again for reminders, such as how to create a new column in your data frame.</p>
<p>Before we leave the console (and to be honest, we won’t exactly leave it behind), we’ll enter one last line of code for now:</p>
<ol start="22" style="list-style-type: decimal">
<li>Type in <code>install.packages("tidyverse")</code> into the console and execute.</li>
</ol>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="co"># Install the tidyverse library</span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="kw">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</a></code></pre></div>
<p>Leave this code to run - it might take some time but you won’t need to worry about this until you’ve moved onto the practical section.</p>
<p>Now we’re ready to move onto our next section, but first - after reading the Tips and recap below - I recommend you take a <strong>long break</strong> from this workbook!</p>
<div class="note">
<p><strong>Tips &amp; Tricks</strong><br></p>
<ul>
<li><p>R is case-sensitive so you need to make sure that you capitalise everything correctly if required.</p></li>
<li><p>The spaces between the words don’t matter but the positions of the commas and brackets do. Remember, if you find the prompt, <code>&gt;</code>, is replaced with a <code>+</code> it is because the command is incomplete. If necessary, hit the escape (esc) key and try again.</p></li>
<li><p>It is important to come up with good names for your objects. In the case of the majority of our variables, we used a underscore <code>_</code> to separate the words. It is good practice to keep the object names as short as posssible but they still need to be easy to read and clear what they are referring to. Be aware: <strong>you cannot start an object name with a number!</strong></p></li>
<li>If you press the up arrow in the command line you will be able to edit the previous lines of code you have inputted.</li>
</ul>
</div>
<div class="codetime">
<p><strong>Coding Breakthroughs</strong><br></p>
<p>In this section you have:</p>
<ol style="list-style-type: decimal">
<li>Entered your first commands into the R command line interface.</li>
<li>Created objects in R.</li>
<li>Created a vector of values.</li>
<li>Executed some simple R functions.</li>
<li>Created a data frame.</li>
</ol>
</div>
<br>
<center>
<strong>Now, please, make sure you go ahead and take a break!</strong>
</center>
<p><br></p>
</div>
</div>
<div id="the-tidyverse-philosophy-and-principles" class="section level3 unnumbered">
<h3>The Tidyverse Philosophy and Principles</h3>
<p>Over the past weeks a lot of information has come your way, diving deep into the world of GIScience…and now programing.</p>
<p>However, whilst you are slowly becoming proficient in using spatial data and hopefully enjoying learning about how to code, we also need to learn about how our <strong>data</strong> is <strong>structured</strong> aand <strong>organised</strong>.</p>
<br>
<center>
<strong>I told you there were quite a few learning curves in this module!</strong>
</center>
<p><br></p>
<p>This is crucial for when you are moving on to working on your own projects where you have to source data yourselves: the vast majority of the data you will find in the public domain (or private domain for that matter) will be what’s becoming colloquially called: <em>dirty data</em>.</p>
<p>What we mean by dirty data is data that needs some form of pre-processing, cleaning, and linkage before you can use it for your analysis.</p>
<p>Let’s think back to the Ward and Borough Population data that you downloaded from the ONS - we could not use the Excel Spreadsheet straight away as it was within a large workbook with a) many tabs and b) lots of additional formatting (e.g. empty rows, “whitespace”).</p>
<p>Instead, we extracted the data we wanted and formatted it into a very simple table, consisting of only fields that contained individual records for each of our Wards or Boroughs.</p>
<p>This table would fit what is understood as the <strong>tidy data</strong> approach, which is a general perspective on how to structure your data in R to ease its analysis.</p>
<p><strong>Tidy data</strong> was formalised by R Wizard Hadley Wickham in his contribution to the Journal of Statistical Software as a way of consistently structuring your data.</p>
<p>In the words, of the Wizard:</p>
<blockquote>
<p>Once you have tidy data and the tidy tools provided by packages in the tidyverse, you will spend much less time munging data from one representation to another, allowing you to spend more time on the analytic questions at hand.</p>
</blockquote>
<p>This <strong>tidy data</strong> approach is very much at the core of the tidyverse R package that we just installed - and for us as soon-to-be connoisseurs of secondary data, is also of significant importance when organising your data for future projects.</p>
<p>So what do tidy data look like?</p>
<div id="tidy-data-in-practice" class="section level4 unnumbered">
<h4>Tidy Data In Practice</h4>
<p>Believe it or not, you can often represent the same underlying data in multiple ways.</p>
<p>The example below, taken from the the tidyverse package and described in the R for Data Science book, shows that the same data can organised in four different ways.</p>
<p>The data shows the population and cases (of something, e.g. malaria) for each country, for 1999 and 2000:</p>
<p><img src="images/w4/tidydata.png" width="534" style="display: block; margin: auto;" /></p>
<p>None of these representations are wrong per se, however, not are equally easy to use.</p>
<p>Only Table <strong>1</strong> can be considered as tidy data because it is the only table that adheres to the three rules that make a dataset tidy:</p>
<ol style="list-style-type: decimal">
<li><strong>Each variable must have its own column.</strong></li>
<li><strong>Each observation must have its own row.</strong></li>
<li><strong>Each value must have its own cell.</strong></li>
</ol>
<p>In the case of Table 4 - we even have two tables!</p>
<p>These three rules are interrelated because it’s impossible to only satisfy two of the three. That interrelationship leads to an even simpler set of practical instructions:</p>
<ol style="list-style-type: decimal">
<li><p>Put each dataset in a table/data frame/tibble.</p></li>
<li><p>Put each variable in a column.</p></li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:04-figure-hadley-wickham"></span>
<img src="images/w4/04_a_tidy_data.png" alt="A visual representation of tidy data by [Hadley Wickham](https://r4ds.had.co.nz/tidy-data.html)." width="960" />
<p class="caption">
Figure 4.1: A visual representation of tidy data by <a href="https://r4ds.had.co.nz/tidy-data.html">Hadley Wickham</a>.
</p>
</div>
<p><strong>Why ensure that your data is tidy?</strong></p>
<p>Well, there are two main advantages (according to Hadley Wickham):</p>
<ul>
<li><p>There’s a general advantage to picking one consistent way of storing data. If you have a consistent data structure, it’s easier to learn the tools that work with it because they have an underlying uniformity.</p></li>
<li><p>There’s a specific advantage to placing variables in columns because it allows R’s vectorised nature to shine. As you learned in mutate and summary functions, most built-in R functions work with vectors of values. That makes transforming tidy data feel particularly natural.</p></li>
</ul>
<p>We’ll see all of this in action over the coming weeks - but if you’d like, you can hear this explanation directly from one of R-Studio’s very own resident Data Scientists below.</p>
<p>You don’t need to listen to the whole video, but from the beginning until approximately 7:40mins.</p>
<center>
<strong>Tidy Data in R* {-}</strong>
</center>
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/1ELALQlO-yM" width="533" height="300" frameborder="0" allowfullscreen=""></iframe>
</div>
</div>
<p>The <strong>R-Studio Youtube</strong> channel is also generally a great resource for you to be aware of as you pursue your learning in R.</p>
</div>
<div id="so-what-is-the-tidyverse" class="section level4 unnumbered">
<h4>So what is the Tidyverse?</h4>
<p>The tidyverse is a collection of packages that are specifically designed for these data sciencey tasks of data wrangling, management, cleaning, analysis and visualisation within R-Studio.</p>
<p><em>Our earlier lecture introduced you to the concept of a package - but they are explained in more detail below.</em></p>
<p>Whilst in many cases different packages work all slightly differently, all packages of the tidyverse share the underlying design philosophy, grammar, and data structures as we’ll see over the coming weeks.</p>
<p>The tidyverse itself is treated and loaded as a single package, but this means if you load the tidyverse package within your script (through <code>library(tidyverse)</code>), you will directly have access to all the functions that are part of each of the packages that are within the overall tidyverse. This means you do not have to load each package seperately - saving us lines of code, sweet!</p>
<p>We’ve already gone ahead and executed the code to install the tidyverse within our various versions of R - but because the tidyverse consists of multiple packages, it may take a little while before everything is installed so be patient!</p>
<p>For more information on tidyverse, have a look at <a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a>.</p>
<p><strong>How does the tidyverse help with tidying data?</strong></p>
<p>There are some specific functions in <code>tidyverse</code> suite of packages that will help us cleaning and preparing our datasets to create a <strong>tidy dataset</strong>.</p>
<p>The most important and useful functions, from the <code>tidyr</code> and <code>dplyr</code> packages, are:</p>
<table>
<thead>
<tr class="header">
<th align="left">Package</th>
<th align="left">Function</th>
<th align="left">Use to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">select</td>
<td align="left">select columns</td>
</tr>
<tr class="even">
<td align="left">dplyr</td>
<td align="left">filter</td>
<td align="left">select rows</td>
</tr>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">mutate</td>
<td align="left">transform or recode variables</td>
</tr>
<tr class="even">
<td align="left">dplyr</td>
<td align="left">summarise</td>
<td align="left">summarise data</td>
</tr>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">group by</td>
<td align="left">group data into subgropus for further processing</td>
</tr>
<tr class="even">
<td align="left">tidyr</td>
<td align="left">pivot_longer</td>
<td align="left">convert data from wide format to long format</td>
</tr>
<tr class="odd">
<td align="left">tidyr</td>
<td align="left">pivot_wider</td>
<td align="left">convert long format dataset to wide format</td>
</tr>
</tbody>
</table>
<p>These functions all complete very fundamental tasks that we need to manipualte and wrangle our data.</p>
<p>We will get to use these over the coming weeks, so do not panic about trying to remember them all right now.</p>
<div class="codetime">
<p><strong>Installing and using Libraries/Packages for Data Analysis</strong><br></p>
<p>As you will have heard in our earlier lecture, our common Data Analysis languages, including Python and R, have developed large community bases and as a result there are significant amount of help and support resources for those working in data science.</p>
<p>Beyond help and support, these large community bases have been essential for expanding the utility of a programming language for specific types of data analysis.</p>
<p>This is because of how programming languages work – they have a core library of functions to do certain things, such as calculate the mean of a dataset as we did earlier.</p>
<p>But to do more specific or specialized analysis, such as create a buffer around a point, a function needs to be written to enable this.</p>
<p>You either need to write the function yourself – or hope that someone else has written it – plus you need to know that there is the supporting functions around it. E.g. your code can “read” your spatial data and know a) its spatial and b) the projection system its in to calculate a distance.</p>
<p>Without this, you won’t be able to run your function or do your analysis.</p>
<p>These community bases have identified these gaps, such as for spatial data reading and analysis, and spent considerable amount of time writing these functions and supporting functions to add to the core library.</p>
<p>These functions often get packaged into an additional library (or can be called a package) that you add to your own core library by installing this library to your computer AND then importing it to your work through your script.</p>
<p>The <code>tidyr</code> and <code>dplyr</code> packages with the tidyverse are just two examples of these additional libraries created by the wider R community.</p>
<p>The code you just ran asked <strong>R-Studio</strong> to fetch and install the <code>tidyverse</code> into your R-Studio - so this means we’ll be able to use these libraries in our practical below simply by using the <code>library(tidyverse)</code> code at the top of our script.</p>
<p>One thing we need to be <strong>aware</strong> of when it comes to using functions in these <strong>additional</strong> libraries, is that sometimes these functions are called the same thing as the base <strong>R</strong> package, or even, in some cases, another additional library.</p>
<p>We therefore often need to specify which library we want to use this function from, and this can be done with a simple command (<code>library::function</code>) in our code - as we’ll see in practice over the next few weeks, so just make a mental note of this for now.</p>
</div>
<p>Whilst we’ve gone ahead and installed the tidyverse, each time we start a new script, we’ll need to load the tidyverse.</p>
<p>We are going to show all of this in our next Prcatical, which gets you to analyse crime in London whilst putting into place everything we’ve been dicussing today.</p>
<hr />
</div>
</div>
<div id="practical-3-analysing-crime-in-2020-in-london" class="section level3 unnumbered">
<h3>Practical 3: Analysing Crime in 2020 in London</h3>
<p>Wow, we’ve got through a lot today - and barely even started our practical!</p>
<p>But, what I can say, is that there is not a substantial more to learn in terms of principles and practicalities of programming beyond building up your “dictionary/vocabulary” of programming libraries and respective commands.</p>
<p>There are some <strong>more complicated</strong> coding things we can do, such as <code>for</code> and <code>while</code> loops and <code>if</code> statements, but, for now, consider yourself a solid beginner programmer.</p>
<p>As a result, we’re ready to put this all into practice in our practical today, which will be relatively short in comparison to everything you’ve been through above.</p>
<p>What we’ll be doing today is running an exploratory data analysis, using basic statistics, of crime in London over a <strong>monthly</strong> basis.</p>
<p>Let’s get started.</p>
<div id="setting-up-r-studio-for-geog0030" class="section level4 unnumbered">
<h4>Setting Up R-Studio for GEOG0030</h4>
<p>In the previous section, R may have seemed fairly labour-intensive. We had to enter all our data manually and each line of code had to be written into the command line. Fortunately this isn’t routinely the case.</p>
<p>In RStudio, we can use <strong>scripts</strong> to build up our code that we can run repeatedly - and save for future use.</p>
<p>Before we start a new script, we first want to set up ourselves ready for the rest of our practicals by <strong>creating a new project</strong>.</p>
<p>To put it succintly, <strong>projects</strong> in R-Studio keep all the files associated with a project together — input data, R scripts, analytical results, figures.</p>
<p>This means we can easily keep track of - and access - inputs and outputs from different weeks across our module, whilst still creating standalone scripts for each bit of processing analysis we do.</p>
<p>It also makes dealing with <strong>directories</strong> and <strong>paths</strong> a whole lot easier - particularly if you <strong>have followed the folder structure I advised at the start of the module</strong>.</p>
<p>Let’s go ahead and make a <strong>New Project</strong> directly within our <strong>GEOG0030</strong> folder.</p>
<ol style="list-style-type: decimal">
<li>Click on <strong>File -&gt; New Project –&gt; Existing Directory</strong> and browse to your <strong>GEOG0030</strong> folder. Click on <strong>Create Project</strong>.</li>
</ol>
<p><img src="images/w4/new-project.png" width="650pt" style="display: block; margin: auto;" /></p>
<p>You should now see your main window switch to this new project - and if you check your <strong>Files</strong> window, you should now see a new <strong>R Project</strong> called <strong>GEOG0030</strong>:</p>
<p><img src="images/w4/r-project.png" width="150pt" style="display: block; margin: auto;" /></p>
<p>We are now “in” the GEOG0030 project - and any folders within the GEOG0030 project can be easily accessed by our code. Furthermore, any scripts we create will be saved in this project. Note, there is not a “script” folder per se, but rather your scripts will simply exist in this project.</p>
<p>You can test this change of directly by selecting the <strong>Terminal</strong> window (next to your <strong>Console</strong> window) to access the Terminal in R-Studio and type our <code>pwd</code> command. You should see that our current directory is your GEOG0030 folder.</p>
<div class="reading">
<p><strong>R for Data Science by Hadley Wickham and Garret Grolemund</strong><br><br>
Your only key reading for this week is to read through the <strong>R for Data Science</strong> handbook - although you can take each section at your own leisure over the coming weeks.
For this week, I’d highly recommend reading more about why we use <a href="https://r4ds.had.co.nz/workflow-projects.html">Projects</a>, whilst this section tells us more about <a href="https://r4ds.had.co.nz/workflow-scripts.html">Scripts</a>. I’d stick with these sections for now, but have a quick glance at what’s available in the book.</p>
</div>
<p><strong>Setting up our script</strong></p>
<p>In our shorter practical sessions above, we’ve had a bit of fun playing with the R code within the R console and seeing how we can store variables and access information about them. Furthermore, we’ve had a look at the different data structures we may use moving forward.</p>
<p>But ultimately this really doesn’t offer the functionality that we want for our work - or even the reality of what we need to do with spatial analysis.</p>
<p>What we really want to do is to start building <strong>scripts</strong> and add start analysing some data!</p>
<p>Therefore, for the majority of our analysis work, we will type our code <strong>within a script</strong> and not the console.</p>
<p>Let’s create our first script:</p>
<ol start="2" style="list-style-type: decimal">
<li>Click on <strong>File -&gt; New File –&gt; R Script</strong>.
<ul>
<li>You can also use the plus symbol over a white square as a shortcut or even <strong>Ctrl/CMD + Shift + N</strong>.</li>
</ul></li>
</ol>
<p>This should give you a blank document that looks a bit like the command line. The difference is that anything you type here can be saved as a script and re-run at a later date.</p>
<p><img src="images/w4/04_rstudio_interface_script.png" width="650pt" style="display: block; margin: auto;" /></p>
<p>Let’s go ahead and save this script straight away.</p>
<ol start="3" style="list-style-type: decimal">
<li>Save your script as: <code>wk4-csv-processing.r</code>.</li>
</ol>
<p>Through our name, we know now that our script was created in Week 4 of Geocomputation and the code it will contain is something to do with csv processing. This will help us a lot in the future when we come to find code that we need for other projects.</p>
<p>I personally tend to use <strong>one script</strong> per type of processing <strong>or</strong> analysis that I’m completing.</p>
<p>For example, if you are doing <strong>a lot</strong> of data cleaning to create a final dataset that you’ll then analyse, its best practice to separate this from your analysis script so you do not continually clean your raw datasets when you run your script.</p>
<p><strong>Giving our script some metadata</strong></p>
<p>The <strong>first</strong> bit of code you will want to add to any script is to add a <strong>TITLE</strong>. This title should give any reader a quick understanding of what your code achieves.</p>
<p>When writing a script it is important to keep notes about what each step is doing. To do this, the hash (<code>#</code>) symbol is put before any code. This comments out that particular line so that R ignores it when the script is run.</p>
<p>Let’s go ahead and give our script a <strong>TITLE</strong> - and maybe some additional information:</p>
<ol start="4" style="list-style-type: decimal">
<li>Add the following to your script (substitute accordingly):</li>
</ol>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="co"># Combining Police Data csvs from 2020 into a single csv</span></a>
<a class="sourceLine" id="cb65-2" title="2"><span class="co"># Followed by analysis of data on monthly basis</span></a>
<a class="sourceLine" id="cb65-3" title="3"><span class="co"># Script started January 2021</span></a>
<a class="sourceLine" id="cb65-4" title="4"><span class="co"># NAME</span></a></code></pre></div>
<p>Save your script.</p>
<p><strong>Load Our Libraries</strong></p>
<p>Now we have our title, the <strong>second</strong> bit of code we want to include in our script is to load <strong>our libraries</strong> (i.e. the installed packages we’ll need in our script):</p>
<ol start="5" style="list-style-type: decimal">
<li>Type the following into the script:</li>
</ol>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="co"># Libraries used in this script:</span></a>
<a class="sourceLine" id="cb66-2" title="2"><span class="co"># Load the tidyverse library</span></a>
<a class="sourceLine" id="cb66-3" title="3"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<p>By loading simply the <code>tidyverse</code>, we have a pretty good estimate that we’ll be able to access all the functions that we’re going to need today.</p>
<p>However, often when developing a script, you’ll realise that you’ll need to add libraries as you go along in order to use a specific function etc.</p>
<p>When you do this, <strong>always add your library to the top of your script</strong> - if you ever share your script, it helps the person you are sharing with recognise quickly if they need to install any additional packages prior to trying to run the script. It also means your libraries do not get lost in the multiple lines of code you are writing.</p>
<p><strong>Setting Up Our Directory</strong></p>
<p>Understanding and accessing our directory path used to be the worst part of programming. And if you do not use the Project approach advocated above, it certainly will continue to be.</p>
<p>If, for example, we did not use a project approach, we would need to <strong>set</strong> our working directory directly within our script using the command:</p>
<p><code>setwd("file/path/to/GEOG0030)</code></p>
<p>We’d therefore need to know what our path is and hope we do not make any mistakes. There are some automated shortcuts to doing this in R using the Files window, but ultimately, having to set a working directory is becoming a thing of the past.</p>
<p>Because we are using a project approach - we do not need to set a working directory - because we’re already in it!</p>
<p>Therefore, when looking for data in our folders, we know pretty much the path we’ll need to take.</p>
<p>However, we still might need to access data from another folder outside of our GEOG0030 folder - so we need to know how to do this.</p>
<p>To help with this, we’re going ot add one more library to our library list, called the <code>here</code> library. We won’t go into too much detail what this library does per se, but essentially it alows you to direct R to a specific area on your computer and a specific file with relative ease.</p>
<p>We actually won’t use it in this practical, but I wanted to get you into the habit of adding it to your scripts by default.</p>
<p>First, you’ll need to install this library to your computer.</p>
<ol start="6" style="list-style-type: decimal">
<li>In your <strong>Console</strong> window, type and execute:</li>
</ol>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1"><span class="co"># Install the here library via your console</span></a>
<a class="sourceLine" id="cb67-2" title="2"><span class="kw">install.packages</span>(<span class="st">&quot;here&quot;</span>)</a></code></pre></div>
<p>Once installed, we can go ahead and load this after our tidyverse library - your script should look like so:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="co"># Libraries used in this script:</span></a>
<a class="sourceLine" id="cb68-2" title="2"><span class="co"># Load the tidyverse library</span></a>
<a class="sourceLine" id="cb68-3" title="3"><span class="co"># Load the here library</span></a>
<a class="sourceLine" id="cb68-4" title="4"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb68-5" title="5"><span class="kw">library</span>(here)</a></code></pre></div>
<p>One thing to note, not only does installing and loading libraries need to occur in two different parts of R-Studio, but when installing, your library needs to be in <strong>""</strong> but when loading, it does not.</p>
<div class="codetime">
<p><strong>File and folder names best practice</strong><br></p>
<p>Please ensure that <strong>folder names</strong> and <strong>file names</strong> do not contain spaces or special characters such as <code>*</code> <code>.</code> <code>"</code> <code>/</code> <code>\</code> <code>[</code> <code>]</code> <code>:</code> <code>;</code> <code>|</code> <code>=</code> <code>,</code> <code>&lt;</code> <code>?</code> <code>&gt;</code> <code>&amp;</code> <code>$</code> <code>#</code> <code>!</code> <code>'</code> <code>{</code> <code>}</code> <code>(</code> <code>)</code>.</p>
<p>Different operating systems and programming languages deal differently with spaces and special characters and as such including these in your folder names and file names can cause many problems and unexpected errors.</p>
<p>As an alternative to using white space you can use an underscore <code>_</code> if you like.</p>
</div>
<p>Remember to save your script.</p>
<p>We’re now ready to run these first two lines of code.</p>
</div>
<div id="running-a-script-in-r-studio" class="section level4 unnumbered">
<h4>Running a script in R-Studio</h4>
<p>There are two main ways to run a script in R-Studio - all at once or by line/chunk by line/chunk.</p>
<p>It can be advantageous to pursue with the second option as you first start out to build your script as it allows you to test your code iteratively.</p>
<p><strong>To run line-by-line:</strong></p>
<p>By clicking:</p>
<ul>
<li>Select the line or chunk of code you want to run, then click on <strong>Code</strong> and choose <strong>Run selected lines</strong>.</li>
</ul>
<p>By key commands:</p>
<ul>
<li>Select the line or chunk of code you want to run and then hold <strong>Ctl</strong> or <strong>Cmd</strong> and press <strong>Return</strong>.</li>
</ul>
<p><strong>To run the whole script</strong></p>
<p>By clicking:</p>
<ul>
<li>Click on <strong>Run</strong> on the top-right of the scripting window and choose <strong>Run All</strong>.</li>
</ul>
<p>By key commands:</p>
<ul>
<li>Hold <strong>Option</strong> plus <strong>Ctl</strong> or <strong>Cmd</strong> and <strong>R</strong>.</li>
</ul>
<p><strong>Stopping a script from running</strong></p>
<p>If you are running a script that seems to be stuck (for whatever reason) or you notice some of your code is wrong, you will need to <strong>interrupt</strong> R.</p>
<p>To do so, click on <strong>Session -&gt; Interrupt R</strong>. If this does not work, you may end up needing to <strong>Terminate R</strong> but this may lose any unsaved progress.</p>
<div class="codetime">
<p><strong>Run your code line-by-line</strong><br></p>
<p>In this practical, I recommend <strong>running each line (or set of lines) of code you enter as you go</strong> - rather than wait til the end and execute the whole script.
This way you will be able to find any bugs as you go along.</p>
<p><strong>Don’t forget to scroll to the top of your script and execute your library loads!</strong></p>
</div>
</div>
<div id="data-import-and-processing" class="section level4 unnumbered">
<h4>Data Import and Processing</h4>
<p>We’re now ready to get started with using the crime data csvs currently sat in our <code>all_crime</code> folder.</p>
<p>To do so, we need to first figure out how to import the csv and understand the data structure it will be in after importing.</p>
<p><strong>Importing and loading Data</strong></p>
<p>To read in a csv into R requires the use of a very simple function: <code>read_csv()</code>.</p>
<p>We can look at the help documentation to understand what we need to provide the function (or rather the optional arguments), but as we just want to load single csv, we’ll go ahead and just use the function with a simple parameter.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="co"># Read in a single csv from our crime data</span></a>
<a class="sourceLine" id="cb69-2" title="2">crime_csv &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/raw/crime/all_crime/2020-11-metropolitan-street.csv&quot;</span>)</a></code></pre></div>
<p>We can explore the csv we have just loaded as our new <code>crime_csv</code> variable and understand the class, attributes and dimensions of our variable.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="co"># Check class and dimensions of our data frame</span></a>
<a class="sourceLine" id="cb70-2" title="2"><span class="co"># you can also check the attributes if you would like - this will load up a huge list of every row though!</span></a>
<a class="sourceLine" id="cb70-3" title="3"><span class="kw">class</span>(crime_csv)</a></code></pre></div>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;         &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">dim</span>(crime_csv)</a></code></pre></div>
<pre><code>## [1] 96914    12</code></pre>
<p>We’ve found out our variable is a data frame, containing <strong>96914 rows and 12 columns</strong>.</p>
<p>We can also tell it’s a big file - so best not load it up right now.</p>
<p>We however do not want just the single <code>csv</code> and instead what to combine all our csvs in our <code>all_crime</code> folder into a single dataframe - so how do we do this?</p>
<p><strong>Joining all of our csvs files together into a single data frame</strong></p>
<p>This will be the most complicated section of code you’ll come across today, and we’ll use some functions that you’ve not seen before - we also need to install and load an additional library to use something known as a <strong>pipe function</strong> which I’ll explain in more detail next week.</p>
<p>In your console, install the <code>magrittr</code> package:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1"><span class="co"># Install the magrittr library via your console</span></a>
<a class="sourceLine" id="cb74-2" title="2"><span class="kw">install.packages</span>(<span class="st">&quot;magrittr&quot;</span>)</a></code></pre></div>
<p>And in your <code># Load libraries</code> section of your script, add the <code>magrittr</code> library. Your library section should look like this:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="co"># Libraries used in this script:</span></a>
<a class="sourceLine" id="cb75-2" title="2"><span class="co"># Load the tidyverse library</span></a>
<a class="sourceLine" id="cb75-3" title="3"><span class="co"># Load the here library</span></a>
<a class="sourceLine" id="cb75-4" title="4"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb75-5" title="5"><span class="kw">library</span>(here)</a>
<a class="sourceLine" id="cb75-6" title="6"><span class="kw">library</span>(magrittr)</a></code></pre></div>
<p><strong>Remember to execute the loading of the <code>magrittr</code> library by selecting the line and running the code.</strong></p>
<p>Now we’re ready to add and run the following code:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="co"># Read in all csvs and append all rows to a single data frame</span></a>
<a class="sourceLine" id="cb76-2" title="2">all_crime_df &lt;-<span class="st"> </span><span class="kw">list.files</span>(<span class="dt">path=</span><span class="st">&quot;data/raw/crime/all_crime&quot;</span>, <span class="dt">full.names=</span><span class="ot">TRUE</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb76-3" title="3"><span class="st">  </span><span class="kw">lapply</span>(read_csv) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb76-4" title="4"><span class="st">  </span>bind_rows</a></code></pre></div>
<p>This might take a little time to process (or might not), as we have a lot of data to get through.</p>
<p>You should see a new datafarme appear in your global environment called <code>all_crime</code>, for which we now have 1,099,507 observations!</p>
<div class="codetime">
<p><strong>Explaining the above code</strong><br></p>
<p>It is a little difficult to explain the code above without going into a detail explanation of what a pipe is (next week) but essentially what these three lines of code does is:</p>
<ol style="list-style-type: decimal">
<li><p>List of of the files found in the data path: <code>"data/raw/crime/all_crime</code></p></li>
<li><p>Read each of these as a csv (this is the <code>lapply()</code> function) in as a dataframe</p></li>
<li><p>And then bind the rows of these dataframes to a single dataframe called <code>all_crime_df</code></p></li>
</ol>
<p>We’ll go into more detail about pipes next week.</p>
</div>
<p>We can now have a look at our large dataframe in more detail.</p>
<p>Let’s have a look</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="co"># Understand our all_crime_df cols, rows and print the first five rows</span></a>
<a class="sourceLine" id="cb77-2" title="2"><span class="kw">ncol</span>(all_crime_df)</a></code></pre></div>
<pre><code>## [1] 12</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">nrow</span>(all_crime_df)</a></code></pre></div>
<pre><code>## [1] 1099507</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">head</span>(all_crime_df)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 12
##   `Crime ID` Month `Reported by` `Falls within` Longitude Latitude Location
##   &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   
## 1 37c663d86… 2020… City of Lond… City of Londo…   -0.106      51.5 On or n…
## 2 5b89923fa… 2020… City of Lond… City of Londo…   -0.118      51.5 On or n…
## 3 fb3350ce8… 2020… City of Lond… City of Londo…   -0.113      51.5 On or n…
## 4 07172682a… 2020… City of Lond… City of Londo…   -0.112      51.5 On or n…
## 5 14e02a604… 2020… City of Lond… City of Londo…   -0.111      51.5 On or n…
## 6 &lt;NA&gt;       2020… City of Lond… City of Londo…   -0.0980     51.5 On or n…
## # … with 5 more variables: `LSOA code` &lt;chr&gt;, `LSOA name` &lt;chr&gt;, `Crime
## #   type` &lt;chr&gt;, `Last outcome category` &lt;chr&gt;, Context &lt;lgl&gt;</code></pre>
<p>You should now see with have the same number of columns as our previous single csv, <strong>but</strong> 1,099,507 rows!</p>
<p>You can also see that the <code>head()</code> function provides us with the first <strong>five</strong> rows of our dataframe. You can conversely use <code>tail()</code> to provide the last five rows.</p>
<p><strong>Filtering our data to a new variable</strong></p>
<p>For now in our analysis, we only want to extract the <strong>theft</strong> crime in our dataframe - so we will want to filter our data based on the <strong>Crime type</strong> column.</p>
<p>However, as we can see, we have a space in our field name for <strong>Crime type</strong> and, in fact, many of the other fields.</p>
<p>As we want to avoid having spaces in our field names when coding (or else our code will break!), we need to rename our fields.</p>
<p>To do so, we’ll first get all of the names of our fields so we can copy and paste these over into our code:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="co"># Get the field names of our all_crime_df</span></a>
<a class="sourceLine" id="cb83-2" title="2"><span class="kw">names</span>(all_crime_df)</a></code></pre></div>
<pre><code>##  [1] &quot;Crime ID&quot;              &quot;Month&quot;                 &quot;Reported by&quot;          
##  [4] &quot;Falls within&quot;          &quot;Longitude&quot;             &quot;Latitude&quot;             
##  [7] &quot;Location&quot;              &quot;LSOA code&quot;             &quot;LSOA name&quot;            
## [10] &quot;Crime type&quot;            &quot;Last outcome category&quot; &quot;Context&quot;</code></pre>
<p>We can now copy over these values into our code to create a new <strong>vector</strong> variable that contains these field names, updated without spaces.</p>
<p>We can then rename the field names in our dataset - just as we did with our GISS table earlier:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="co"># # Create a new vector containing updated no space / no capital field names</span></a>
<a class="sourceLine" id="cb85-2" title="2">no_space_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;crime_id&quot;</span>, <span class="st">&quot;month&quot;</span>, <span class="st">&quot;reported_by&quot;</span>, <span class="st">&quot;falls_within&quot;</span>, <span class="st">&quot;longitude&quot;</span>,<span class="st">&quot;latitude&quot;</span>, <span class="st">&quot;location&quot;</span>, <span class="st">&quot;lsoa_code&quot;</span>, <span class="st">&quot;lsoa_name&quot;</span>, <span class="st">&quot;crime_type&quot;</span>, <span class="st">&quot;last_outcome_category&quot;</span>, <span class="st">&quot;context&quot;</span>)</a>
<a class="sourceLine" id="cb85-3" title="3"></a>
<a class="sourceLine" id="cb85-4" title="4"><span class="co"># Rename our df field names using these new names</span></a>
<a class="sourceLine" id="cb85-5" title="5"><span class="kw">names</span>(all_crime_df) &lt;-<span class="st"> </span>no_space_names</a></code></pre></div>
<p><em>Note, we could have cleaned our data further and so would only needed to rename a few columns using slicing - but we’ll save data frame slicing for next week!</em>.</p>
<p>We now have our dataframe ready for filtering - and to do so, we’ll use the <code>filter()</code> function for the <code>dplyr</code> library.</p>
<p>This function is really easy to use - but there is also a <code>filter()</code> function in the R base library - that does something different to the function in <code>dplyr</code>.</p>
<p>As a result, we need to use a specific type of syntax - <code>library::function</code> - to tell R to look for and use the the filter function from the <code>dplyr</code> library rather than the default base library.</p>
<p>We then also need to populate our <code>filter()</code> function wsith the necessary paramteres to extract only the “Theft from the person” crime type. This includes providing the function with our main dataframe <strong>plus</strong> the filter query, as outliend below:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1"><span class="co"># Filter all_crime_df to contain only theft, store as a new variable: all_theft_df</span></a>
<a class="sourceLine" id="cb86-2" title="2">all_theft_df &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(all_crime_df, crime_type <span class="op">==</span><span class="st"> &#39;Theft from the person&#39;</span>)</a></code></pre></div>
<p>You should now see the new variable appear in your Environment with 28,476 observations.</p>
<p>Great, you’ve completed your first ever filter using programming.</p>
<p>We now want to follow the <strong>tidy data</strong> philosophy and create one final dataframe to allow us to analyse crime in London by month.</p>
<p>To do so, we want to count how many thefts occur each month in London - and luckily for us <code>dplyr</code> has another function that will do this for us, known simply as <code>count()</code>.</p>
<p><em>You perhaps can see already that <code>dplyr</code> is likely to become well-used library by us in Geocomputation…!</em></p>
<p>Go ahead and search the help to understand the <code>count()</code> function - you’ll also see that there is only <strong>one</strong> function called <code>count()</code> so far, i.e. the one in the <code>dplyr</code> library, so we do not need to use the additional syntax we used above.</p>
<p>Let’s go ahead and <strong>count</strong> the number of thefts in London <strong>by month</strong>.</p>
<p>The code for this is quite simple:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="co"># Count in the all_theft_df the number of crimes by month and store as a new dataframe</span></a>
<a class="sourceLine" id="cb87-2" title="2">theft_month_df &lt;-<span class="st"> </span><span class="kw">count</span>(all_theft_df, month)</a></code></pre></div>
<p>We’ve stored the output of our <code>count()</code> function to a new dataframe: <code>theft_month_df</code>.</p>
<p>Go ahead and look at the dataframe to see the output - it’s a very simple table containing simply the month and <code>n</code>, i.e. the number of crimes occuring per month.</p>
<p>We can and should go ahead and rename this column to help with our interpretation of the dataframe.</p>
<p>We’ll use a quick approach to do this, that uses <strong>selection</strong> of the precise column to rename only the second column:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1"><span class="co"># Rename the second column of our new data frame to crime_totals</span></a>
<a class="sourceLine" id="cb88-2" title="2"><span class="kw">names</span>(theft_month_df)[<span class="dv">2</span>] &lt;-<span class="st"> &quot;crime_totals&quot;</span></a></code></pre></div>
<p>This selection is made through the <code>[2]</code> element of code added after the <code>names()</code> function we have used earlier. We’ll look more at selection, slicing and indexing in next week’s practical.</p>
</div>
<div id="data-analysis-distribution-of-crime-in-london-by-month-in-2020" class="section level4 unnumbered">
<h4>Data Analysis: Distribution of Crime in London by month in 2020</h4>
<p>We now have our final dataset ready for our simple analysis for our Assignment.</p>
<div class="assignment">
<p><strong>Assignment 1: Analysis of crime per month in London in 2020</strong></p>
<p>For your assignment this week, I would like you to complete two tasks.</p>
<p><strong>1. Basic statistics</strong></p>
<p>First what I would like you to do, using the code you’ve written previously is to find out:</p>
<ul>
<li><p><strong>What is the mean average crime per month?</strong></p></li>
<li><p><strong>What is the median average crime per month?</strong></p></li>
</ul>
<p>You may also automate the collection of the <strong>max</strong>, <strong>min</strong> and <strong>range</strong> of our crime per month dataframe.</p>
<p><strong>2. Monthly graph</strong></p>
<p>The second thing I would like you to do is present our data on a simple bar chart.</p>
<p>The basic code to generate a bar chart is provide here:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1"><span class="co"># Read in a single csv from our crime data</span></a>
<a class="sourceLine" id="cb89-2" title="2"><span class="kw">barplot</span>(theft_month_df<span class="op">$</span>crime_totals, <span class="dt">main=</span><span class="st">&quot;Crime distribution in London by month in 2020&quot;</span>, <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Jan&quot;</span>, <span class="st">&quot;Feb&quot;</span>, <span class="st">&quot;Mar&quot;</span>, <span class="st">&quot;Apr&quot;</span>, <span class="st">&quot;May&quot;</span>, <span class="st">&quot;Jun&quot;</span>, <span class="st">&quot;Jul&quot;</span>, <span class="st">&quot;Aug&quot;</span>, <span class="st">&quot;Sep&quot;</span>, <span class="st">&quot;Oct&quot;</span>, <span class="st">&quot;Nov&quot;</span>))</a></code></pre></div>
<p><img src="GEOG0030_files/figure-html/04-bar-plot-1.png" width="672" /></p>
<p>As you’ll see, we have added a <strong>Title</strong> to our graph (<code>main=</code> argument), whilst used the <code>names.arg</code> parameter to add the months of the year in along the x-axis.</p>
<p>Using the <code>barplot()</code> documentation, I would like you to figure out how to change the bar chart fill and borders another colour from grey and black respectively.</p>
<p>You may also look to customise your chart further, but primarily I’d like you to work out how to change these colours to something more aesthetically appealing!</p>
<p>You do not need to submit your bar chart this week, but have it ready for your work in Week 5.</p>
</div>
<p>Beyond the assignment, just take a look at your bar chart and how the distribution of crime changed last year…</p>
<p>Well that’s pretty cool, huh?! I wonder what happened in March to make theft from a person decrease so substantially?</p>
<p>We’ve managed to take a dataset of over 1 million records and clean and filter it to provide a chart that actually shows the potential impact of the COVID-19 lockdown on theft crime in London.</p>
<p>Of course, there is a lot more research and exploratory data analysis we’d need to complete before we could really substantiate our findings, but this first chart is certainly a step in the right direction!</p>
<p>Next week, we’ll be doing <strong>a lot</strong> more with our dataset - including <strong>a lot more</strong> data wrangling and of course spatial anlaysis, but hopefully this week has shown you want you can achieve with just a few lines of code.</p>
<p><strong>Now, make sure to save your script, so we can return to it next week.</strong></p>
<p>You do not need to save your workspace - but can do so if you’d like. Saving the workspace will keep any variables generated during your current session saved and available in a future session.</p>
<hr />
</div>
<div id="extension-activity-mapping-other-crime-type-distributions-across-london" class="section level4 unnumbered">
<h4>Extension Activity: Mapping Other Crime Type Distributions Across London</h4>
<p>If you’ve whizzed through this workshop and would like an additional challenge, you are more than welcome to deploy the code you’ve used above on one or more other crime types in London.</p>
<p>If you remember, each crime is categorised into one of 14 types.</p>
<p>These include:</p>
<table>
<colgroup>
<col width="32%" />
<col width="67%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Crime Type</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">All crime</td>
<td align="left">Total for all categories.</td>
</tr>
<tr class="even">
<td align="left">Anti-social behaviour</td>
<td align="left">Includes personal, environmental and nuisance anti-social behaviour.</td>
</tr>
<tr class="odd">
<td align="left">Bicycle theft</td>
<td align="left">Includes the taking without consent or theft of a pedal cycle.</td>
</tr>
<tr class="even">
<td align="left">Burglary</td>
<td align="left">Includes offences where a person enters a house or other building with the intention of stealing.</td>
</tr>
<tr class="odd">
<td align="left">Criminal damage and arson</td>
<td align="left">Includes damage to buildings and vehicles and deliberate damage by fire.</td>
</tr>
<tr class="even">
<td align="left">Drugs</td>
<td align="left">Includes offences related to possession, supply and production.</td>
</tr>
<tr class="odd">
<td align="left">Other crime</td>
<td align="left">Includes forgery, perjury and other miscellaneous crime.</td>
</tr>
<tr class="even">
<td align="left">Other theft</td>
<td align="left">Includes theft by an employee, blackmail and making off without payment.</td>
</tr>
<tr class="odd">
<td align="left">Possession of weapons</td>
<td align="left">Includes possession of a weapon, such as a firearm or knife.</td>
</tr>
<tr class="even">
<td align="left">Public order</td>
<td align="left">Includes offences which cause fear, alarm or distress.</td>
</tr>
<tr class="odd">
<td align="left">Robbery</td>
<td align="left">Includes offences where a person uses force or threat of force to steal.</td>
</tr>
<tr class="even">
<td align="left">Shoplifting</td>
<td align="left">Includes theft from shops or stalls.</td>
</tr>
<tr class="odd">
<td align="left">Theft from the person</td>
<td align="left">Includes crimes that involve theft directly from the victim (including handbag, wallet, cash, mobile phones) but without the use or threat of physical force.</td>
</tr>
<tr class="even">
<td align="left">Vehicle crime</td>
<td align="left">Includes theft from or of a vehicle or interference with a vehicle.</td>
</tr>
<tr class="odd">
<td align="left">Violence and sexual offences</td>
<td align="left">Includes offences against the person such as common assaults, Grievous Bodily Harm and sexual offences.</td>
</tr>
</tbody>
</table>
<p>You can conduct the same analysis on one or more of these categories in addition to theft, to see if you can find a similar pattern in their prevalance/distribution over the same months.</p>
<hr />
<div class="reading">
<p><strong>R for Data Science by Hadley Wickham and Garret Grolemund</strong><br><br>
As highlighted earlier, your only key reading for this week is to read through the <strong>R for Data Science</strong> handbook - although you can take each section at your own leisure over the coming weeks.</p>
<p>For this week, I’d highly recommend reading more about why we use <a href="https://r4ds.had.co.nz/workflow-projects.html">Projects</a>, whilst this section tells us more about <a href="https://r4ds.had.co.nz/workflow-scripts.html">Scripts</a>.</p>
<p>In addition, you can look at Sections: 1, 2, 4, 11 and 12. I’d stick with these sections for now, but have a quick glance at what else is available in the book. We’ll be looking at Data Transformation (5) and Visualisation (3) next week, plus more on Exploratory Data Analysis (7) in Week 6.</p>
<p>Don’t worry about completing the exercises - unless you would like to!</p>
</div>
</div>
<div id="recap" class="section level4 unnumbered">
<h4>Recap</h4>
<p>In this section you have learnt how to:</p>
<ol style="list-style-type: decimal">
<li>Create an R script.</li>
<li>Load a <code>csv</code> into R, perform some analysis, and write out a new <code>csv</code> file to your
working directory.</li>
<li>Subset R data frames by name and also column and/or row number.</li>
<li>Created a simple graph to plot crime in London by month.</li>
</ol>
<hr />
<div class="sds">
<p><strong>Learning Objectives</strong><br><br>
You should now hopefully be able to:</p>
<ul>
<li>Understand the basics of programming and why it is useful for data analysis</li>
<li>Recognise the differences and purpose of a console command versus the creation of a script</li>
<li>Explain what a library/package is and how to use them in R/R-Studio</li>
<li>Explain the tidyverse philosophy and why it is useful for us as data analysts</li>
<li>Wrangle and manage tabular data to prepare it for analysis</li>
<li>Conduct basic descriptive statistics using R-Studio and R</li>
</ul>
</div>
</div>
<div id="acknowledgements-7" class="section level4 unnumbered">
<h4>Acknowledgements</h4>
<p>Part of this page is adapted from <a href="https://jtvandijk.github.io/POLS0008/understanding-data.html">POLS0008: Understanding Data</a> and <a href="https://jtvandijk.github.io/GEOG0114/exploratory-spatial-data-analysis.html">GEOG0114: Exploratory spatial data analysis</a> by Justin Van Dijk at UCL as well as <a href="https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/">Software Carpentry’s Introduction to R Data Types and Data Structures</a> Copyright © Software Carpentry.</p>
<p>The examples and datasets used in the workbook are original to GEOG0030.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cartography-and-visualisation-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="programming-for-giscience-and-spatial-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jo-wilkin/GEOG0030/edit/master/04-week04.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["https://github.com/jo-wilkin/GEOG0030/raw/master/04-week04.Rmd"],
"toc": {
"collapse": "section",
"toc_depth": 5
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
